//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// XmlSchemaClassGenerator.Console --nullable --namespace http://jpk.mf.gov.pl/wzor/2024/10/30/10302/=ProFak.IO.JPK_PKPIR --namespace http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/=ProFak.IO.JPK_PKPIR.DefinicjeTypy --namespace http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/KodyUrzedowSkarbowych/=ProFak.IO.JPK_PKPIR.KodyUrzedowSkarbowych --namingScheme=Direct Struktura_Schemat_JPK_PKPIR(3)_v1-0.xsd
namespace ProFak.IO.JPK_PKPIR;

    
    
    /// <summary>
    /// <para>Nagłówek JPK_PKPIR</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Nagłówek JPK_PKPIR")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNaglowek", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TNaglowek
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("KodFormularza")]
        public TNaglowekKodFormularza KodFormularza { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("WariantFormularza")]
        public TNaglowekWariantFormularza WariantFormularza { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CelZlozenia")]
        public TCelZlozenia CelZlozenia { get; set; }
        
        /// <summary>
        /// <para>Data i czas wytworzenia JPK_PKPIR</para>
        /// <para>Typ daty i godziny</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data i czas wytworzenia JPK_PKPIR")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DataWytworzeniaJPK", DataType="dateTime")]
        public System.DateTime DataWytworzeniaJPK { get; set; }
        
        /// <summary>
        /// <para>Data początkowa okresu, którego dotyczy JPK_PKPIR</para>
        /// <para>Typ daty</para>
        /// <para xml:lang="en">Minimum inclusive value: 1900-01-01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 2050-12-31.</para>
        /// <para xml:lang="en">Pattern: ((\d{4})-(\d{2})-(\d{2})).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data początkowa okresu, którego dotyczy JPK_PKPIR")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((\\d{4})-(\\d{2})-(\\d{2}))")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.DateTime), "1900-01-01", "2050-12-31")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DataOd", DataType="date")]
        public System.DateTime DataOd { get; set; }
        
        /// <summary>
        /// <para>Data końcowa okresu, którego dotyczy JPK_PKPIR</para>
        /// <para>Typ daty</para>
        /// <para xml:lang="en">Minimum inclusive value: 1900-01-01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 2050-12-31.</para>
        /// <para xml:lang="en">Pattern: ((\d{4})-(\d{2})-(\d{2})).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data końcowa okresu, którego dotyczy JPK_PKPIR")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((\\d{4})-(\\d{2})-(\\d{2}))")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.DateTime), "1900-01-01", "2050-12-31")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DataDo", DataType="date")]
        public System.DateTime DataDo { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("KodUrzedu")]
        public ProFak.IO.JPK_PKPIR.KodyUrzedowSkarbowych.TKodUS KodUrzedu { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNaglowekKodFormularza", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TNaglowekKodFormularza
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public TKodFormularza Value { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _kodSystemowy = "JPK_PKPIR (3)";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("kodSystemowy")]
        public string kodSystemowy
        {
            get
            {
                return _kodSystemowy;
            }
            set
            {
                _kodSystemowy = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _wersjaSchemy = "1-0";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("wersjaSchemy")]
        public string wersjaSchemy
        {
            get
            {
                return _wersjaSchemy;
            }
            set
            {
                _wersjaSchemy = value;
            }
        }
    }
    
    /// <summary>
    /// <para>Symbol wzoru formularza</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Symbol wzoru formularza")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TKodFormularza", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    public enum TKodFormularza
    {
        
        JPK_PKPIR,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNaglowekWariantFormularza", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/", AnonymousType=true)]
    public enum TNaglowekWariantFormularza
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <summary>
    /// <para>Określenie celu złożenia JPK</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Określenie celu złożenia JPK")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCelZlozenia", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    [System.Xml.Serialization.XmlRootAttribute("TCelZlozenia", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    public enum TCelZlozenia
    {
        
        /// <summary>
        /// <para>złożenie JPK na żądanie</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("złożenie JPK na żądanie")]
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <summary>
        /// <para>złożenie JPK po raz pierwszy</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("złożenie JPK po raz pierwszy")]
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <summary>
        /// <para>złożenie korekty JPK</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("złożenie korekty JPK")]
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <summary>
    /// <para>Podstawowy zestaw danych identyfikacyjnych o osobie niefizycznej</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Podstawowy zestaw danych identyfikacyjnych o osobie niefizycznej")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TIdentyfikatorOsobyNiefizycznej", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("TIdentyfikatorOsobyNiefizycznej", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TPodmiotDowolnyBezAdresuOsobaNiefizyczna))]
    public partial class TIdentyfikatorOsobyNiefizycznej
    {
        
        /// <summary>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para xml:lang="en">Pattern: [1-9]((\d[1-9])|([1-9]\d))\d{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identyfikator podatkowy NIP")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]((\\d[1-9])|([1-9]\\d))\\d{7}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("NIP")]
        public string NIP { get; set; }
        
        /// <summary>
        /// <para>Pełna nazwa</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 240.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Pełna nazwa")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(240)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("PelnaNazwa")]
        public string PelnaNazwa { get; set; }
    }
    
    /// <summary>
    /// <para>Skrócony zestaw danych o osobie fizycznej lub niefizycznej z identyfikatorem NIP</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Skrócony zestaw danych o osobie fizycznej lub niefizycznej z identyfikatorem NIP")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TPodmiotDowolnyBezAdresu", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("TPodmiotDowolnyBezAdresu", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JPKPodmiot1))]
    public partial class TPodmiotDowolnyBezAdresu
    {
        
        [System.Xml.Serialization.XmlElementAttribute("OsobaFizyczna")]
        public TPodmiotDowolnyBezAdresuOsobaFizyczna OsobaFizyczna { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OsobaNiefizyczna")]
        public TPodmiotDowolnyBezAdresuOsobaNiefizyczna OsobaNiefizyczna { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TPodmiotDowolnyBezAdresuOsobaFizyczna", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TPodmiotDowolnyBezAdresuOsobaFizyczna : ProFak.IO.JPK_PKPIR.DefinicjeTypy.TIdentyfikatorOsobyFizycznej2
    {
        
        /// <summary>
        /// <para>Adres poczty elektronicznej</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// <para xml:lang="en">Pattern: (.)+@(.)+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(3)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(.)+@(.)+")]
        [System.Xml.Serialization.XmlElementAttribute("Email")]
        public string Email { get; set; }
        
        /// <summary>
        /// <para>Numer telefonu kontaktowego</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 16.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Numer telefonu kontaktowego")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(16)]
        [System.Xml.Serialization.XmlElementAttribute("Telefon")]
        public string Telefon { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TPodmiotDowolnyBezAdresuOsobaNiefizyczna", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TPodmiotDowolnyBezAdresuOsobaNiefizyczna : TIdentyfikatorOsobyNiefizycznej
    {
        
        /// <summary>
        /// <para>Adres poczty elektronicznej</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// <para xml:lang="en">Pattern: (.)+@(.)+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(3)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(.)+@(.)+")]
        [System.Xml.Serialization.XmlElementAttribute("Email")]
        public string Email { get; set; }
        
        /// <summary>
        /// <para>Numer telefonu kontaktowego</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 16.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Numer telefonu kontaktowego")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(16)]
        [System.Xml.Serialization.XmlElementAttribute("Telefon")]
        public string Telefon { get; set; }
    }
    
    /// <summary>
    /// <para>Jednolity plik kontrolny dla podatkowej księgi przychodów i rozchodów</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Jednolity plik kontrolny dla podatkowej księgi przychodów i rozchodów")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JPK", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("JPK", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    public partial class JPK
    {
        
        /// <summary>
        /// <para>Nagłówek JPK_PKPIR</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nagłówek JPK_PKPIR")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Naglowek")]
        public TNaglowek Naglowek { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Podmiot1")]
        public JPKPodmiot1 Podmiot1 { get; set; }
        
        /// <summary>
        /// <para>Dane dotyczące ustalenia dochodu w roku podatkowym</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Dane dotyczące ustalenia dochodu w roku podatkowym")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PKPIRInfo")]
        public JPKPKPIRInfo PKPIRInfo { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<JPKPKPIRSpis> _pKPIRSpis;
        
        /// <summary>
        /// <para>Spisy z natury sporządzone w ciągu roku podatkowego</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Spisy z natury sporządzone w ciągu roku podatkowego")]
        [System.Xml.Serialization.XmlElementAttribute("PKPIRSpis")]
        public System.Collections.ObjectModel.Collection<JPKPKPIRSpis> PKPIRSpis
        {
            get
            {
                return _pKPIRSpis;
            }
            private set
            {
                _pKPIRSpis = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the PKPIRSpis collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PKPIRSpisSpecified
        {
            get
            {
                return (this.PKPIRSpis.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="JPK" /> class.</para>
        /// </summary>
        public JPK()
        {
            this._pKPIRSpis = new System.Collections.ObjectModel.Collection<JPKPKPIRSpis>();
            this._pKPIRWiersz = new System.Collections.ObjectModel.Collection<JPKPKPIRWiersz>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<JPKPKPIRWiersz> _pKPIRWiersz;
        
        [System.Xml.Serialization.XmlElementAttribute("PKPIRWiersz")]
        public System.Collections.ObjectModel.Collection<JPKPKPIRWiersz> PKPIRWiersz
        {
            get
            {
                return _pKPIRWiersz;
            }
            private set
            {
                _pKPIRWiersz = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the PKPIRWiersz collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PKPIRWierszSpecified
        {
            get
            {
                return (this.PKPIRWiersz.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>Sumy kontrolne dla tabeli PKPIRWiersz</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Sumy kontrolne dla tabeli PKPIRWiersz")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PKPIRCtrl")]
        public JPKPKPIRCtrl PKPIRCtrl { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JPKPodmiot1", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JPKPodmiot1 : TPodmiotDowolnyBezAdresu
    {
        
        /// <summary>
        /// <para>Znacznik dla podatnika rozliczającego podatek metodą kasową</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Znacznik dla podatnika rozliczającego podatek metodą kasową")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Kasowy_PIT")]
        public ProFak.IO.JPK_PKPIR.DefinicjeTypy.TWybor1 Kasowy_PITValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Kasowy_PIT property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool Kasowy_PITValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Znacznik dla podatnika rozliczającego podatek metodą kasową</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<ProFak.IO.JPK_PKPIR.DefinicjeTypy.TWybor1> Kasowy_PIT
        {
            get
            {
                if (this.Kasowy_PITValueSpecified)
                {
                    return this.Kasowy_PITValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.Kasowy_PITValue = value.GetValueOrDefault();
                this.Kasowy_PITValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Znacznik dla podatnika, o którym mowa w § 2 ust. 2 rozporządzenia Ministra Finansów w sprawie prowadzenia podatkowej księgi przychodów i rozchodów (rolnik prowadzący działalność gospodarczą)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Znacznik dla podatnika, o którym mowa w § 2 ust. 2 rozporządzenia Ministra Finans" +
            "ów w sprawie prowadzenia podatkowej księgi przychodów i rozchodów (rolnik prowad" +
            "zący działalność gospodarczą)")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Rolnik_PIT")]
        public ProFak.IO.JPK_PKPIR.DefinicjeTypy.TWybor1 Rolnik_PITValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Rolnik_PIT property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool Rolnik_PITValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Znacznik dla podatnika, o którym mowa w § 2 ust. 2 rozporządzenia Ministra Finansów w sprawie prowadzenia podatkowej księgi przychodów i rozchodów (rolnik prowadzący działalność gospodarczą)</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<ProFak.IO.JPK_PKPIR.DefinicjeTypy.TWybor1> Rolnik_PIT
        {
            get
            {
                if (this.Rolnik_PITValueSpecified)
                {
                    return this.Rolnik_PITValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.Rolnik_PITValue = value.GetValueOrDefault();
                this.Rolnik_PITValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _rola = "Podatnik";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("rola")]
        public string rola
        {
            get
            {
                return _rola;
            }
            set
            {
                _rola = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JPKPKPIRInfo", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JPKPKPIRInfo
    {
        
        /// <summary>
        /// <para>Wartość spisu z natury na początek roku podatkowego w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Wartość spisu z natury na początek roku podatkowego w PLN")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("P_1")]
        public decimal P_1 { get; set; }
        
        /// <summary>
        /// <para>Wartość spisu z natury na koniec roku podatkowego w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Wartość spisu z natury na koniec roku podatkowego w PLN")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("P_2")]
        public decimal P_2 { get; set; }
        
        /// <summary>
        /// <para>Razem koszty uzyskania przychodu, wg objaśnień do podatkowej księgi przychodów i rozchodów w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Razem koszty uzyskania przychodu, wg objaśnień do podatkowej księgi przychodów i " +
            "rozchodów w PLN")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("P_3")]
        public decimal P_3 { get; set; }
        
        /// <summary>
        /// <para>Dochód osiągnięty w roku podatkowym, wg objaśnień do podatkowej księgi przychodów i rozchodów w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Dochód osiągnięty w roku podatkowym, wg objaśnień do podatkowej księgi przychodów" +
            " i rozchodów w PLN")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("P_4")]
        public decimal P_4 { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JPKPKPIRSpis", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JPKPKPIRSpis
    {
        
        /// <summary>
        /// <para>Data spisu z natury sporządzonego w ciągu roku podatkowego</para>
        /// <para>Typ daty</para>
        /// <para xml:lang="en">Minimum inclusive value: 1900-01-01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 2050-12-31.</para>
        /// <para xml:lang="en">Pattern: ((\d{4})-(\d{2})-(\d{2})).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data spisu z natury sporządzonego w ciągu roku podatkowego")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((\\d{4})-(\\d{2})-(\\d{2}))")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.DateTime), "1900-01-01", "2050-12-31")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("P_5A", DataType="date")]
        public System.DateTime P_5AValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the P_5A property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool P_5AValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Data spisu z natury sporządzonego w ciągu roku podatkowego</para>
        /// <para>Typ daty</para>
        /// <para xml:lang="en">Minimum inclusive value: 1900-01-01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 2050-12-31.</para>
        /// <para xml:lang="en">Pattern: ((\d{4})-(\d{2})-(\d{2})).</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> P_5A
        {
            get
            {
                if (this.P_5AValueSpecified)
                {
                    return this.P_5AValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.P_5AValue = value.GetValueOrDefault();
                this.P_5AValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Wartość spisu z natury sporządzonego w ciągu roku podatkowego w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Wartość spisu z natury sporządzonego w ciągu roku podatkowego w PLN")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("P_5B")]
        public decimal P_5BValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the P_5B property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool P_5BValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Wartość spisu z natury sporządzonego w ciągu roku podatkowego w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> P_5B
        {
            get
            {
                if (this.P_5BValueSpecified)
                {
                    return this.P_5BValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.P_5BValue = value.GetValueOrDefault();
                this.P_5BValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JPKPKPIRWiersz", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JPKPKPIRWiersz
    {
        
        /// <summary>
        /// <para>Lp.</para>
        /// <para>Liczby naturalne większe od zera</para>
        /// <para xml:lang="en">Total number of digits: 14.</para>
        /// <para xml:lang="en">Minimum exclusive value: 0.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Lp.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("K_1")]
        public ulong K_1 { get; set; }
        
        /// <summary>
        /// <para>Data zdarzenia gospodarczego</para>
        /// <para>Typ daty</para>
        /// <para xml:lang="en">Minimum inclusive value: 1900-01-01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 2050-12-31.</para>
        /// <para xml:lang="en">Pattern: ((\d{4})-(\d{2})-(\d{2})).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data zdarzenia gospodarczego")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((\\d{4})-(\\d{2})-(\\d{2}))")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.DateTime), "1900-01-01", "2050-12-31")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("K_2", DataType="date")]
        public System.DateTime K_2 { get; set; }
        
        /// <summary>
        /// <para>Nr dowodu księgowego</para>
        /// <para>Typ znakowy ograniczony do 256 znaków</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nr dowodu księgowego")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("K_3A")]
        public string K_3A { get; set; }
        
        /// <summary>
        /// <para>Numer identyfikujący fakturę wystawioną przy użyciu Krajowego Systemu e-Faktur (numer KSeF)</para>
        /// <para>Numer identyfikujący fakturę w Krajowym Systemie e-Faktur (KSeF)</para>
        /// <para xml:lang="en">Pattern: ([1-9]((\d[1-9])|([1-9]\d))\d{7}|M\d{9}|[A-Z]{3}\d{7})-(20[2-9][0-9]|2[1-9][0-9]{2}|[3-9][0-9]{3})(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])-([0-9A-F]{6})-?([0-9A-F]{6})-([0-9A-F]{2}).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Numer identyfikujący fakturę wystawioną przy użyciu Krajowego Systemu e-Faktur (n" +
            "umer KSeF)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([1-9]((\\d[1-9])|([1-9]\\d))\\d{7}|M\\d{9}|[A-Z]{3}\\d{7})-(20[2-9][0-9]|2[1-9][0-9]{" +
            "2}|[3-9][0-9]{3})(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])-([0-9A-F]{6})-?([0-9A" +
            "-F]{6})-([0-9A-F]{2})")]
        [System.Xml.Serialization.XmlElementAttribute("K_3B")]
        public string K_3B { get; set; }
        
        /// <summary>
        /// <para>Kod kraju nadania identyfikatora podatkowego</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Kod kraju nadania identyfikatora podatkowego")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("K_4A")]
        public ProFak.IO.JPK_PKPIR.DefinicjeTypy.TKodKraju K_4AValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the K_4A property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool K_4AValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Kod kraju nadania identyfikatora podatkowego</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<ProFak.IO.JPK_PKPIR.DefinicjeTypy.TKodKraju> K_4A
        {
            get
            {
                if (this.K_4AValueSpecified)
                {
                    return this.K_4AValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.K_4AValue = value.GetValueOrDefault();
                this.K_4AValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Numer identyfikacji podatkowej kontrahenta</para>
        /// <para>Numer służący identyfikacji dla celów podatkowych</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Numer identyfikacji podatkowej kontrahenta")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("K_4B")]
        public string K_4B { get; set; }
        
        /// <summary>
        /// <para>Kontrahent - imię i nazwisko (firma)</para>
        /// <para>Typ znakowy ograniczony do 256 znaków</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Kontrahent - imię i nazwisko (firma)")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("K_5A")]
        public string K_5A { get; set; }
        
        /// <summary>
        /// <para>Kontrahent - adres</para>
        /// <para>Typ znakowy ograniczony do 256 znaków</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Kontrahent - adres")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("K_5B")]
        public string K_5B { get; set; }
        
        /// <summary>
        /// <para>Opis zdarzenia gospodarczego</para>
        /// <para>Typ znakowy ograniczony do 256 znaków</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Opis zdarzenia gospodarczego")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("K_6")]
        public string K_6 { get; set; }
        
        /// <summary>
        /// <para>Przychód - wartość sprzedanych towarów i usług w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Przychód - wartość sprzedanych towarów i usług w PLN")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("K_7")]
        public decimal K_7Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the K_7 property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool K_7ValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Przychód - wartość sprzedanych towarów i usług w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> K_7
        {
            get
            {
                if (this.K_7ValueSpecified)
                {
                    return this.K_7Value;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.K_7Value = value.GetValueOrDefault();
                this.K_7ValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Przychód - pozostałe przychody w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Przychód - pozostałe przychody w PLN")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("K_8")]
        public decimal K_8Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the K_8 property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool K_8ValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Przychód - pozostałe przychody w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> K_8
        {
            get
            {
                if (this.K_8ValueSpecified)
                {
                    return this.K_8Value;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.K_8Value = value.GetValueOrDefault();
                this.K_8ValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Przychód - razem przychód w PLN (K_7 + K_8)</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Przychód - razem przychód w PLN (K_7 + K_8)")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("K_9")]
        public decimal K_9Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the K_9 property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool K_9ValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Przychód - razem przychód w PLN (K_7 + K_8)</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> K_9
        {
            get
            {
                if (this.K_9ValueSpecified)
                {
                    return this.K_9Value;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.K_9Value = value.GetValueOrDefault();
                this.K_9ValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Przychód dla rolników prowadzących działalność gospodarczą w PLN (§ 2 ust. 2 rozporządzenia)</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Przychód dla rolników prowadzących działalność gospodarczą w PLN (§ 2 ust. 2 rozp" +
            "orządzenia)")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("K_9A")]
        public decimal K_9AValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the K_9A property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool K_9AValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Przychód dla rolników prowadzących działalność gospodarczą w PLN (§ 2 ust. 2 rozporządzenia)</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> K_9A
        {
            get
            {
                if (this.K_9AValueSpecified)
                {
                    return this.K_9AValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.K_9AValue = value.GetValueOrDefault();
                this.K_9AValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Zakup towarów handlowych i materiałów wg cen zakupu w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Zakup towarów handlowych i materiałów wg cen zakupu w PLN")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("K_10")]
        public decimal K_10Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the K_10 property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool K_10ValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Zakup towarów handlowych i materiałów wg cen zakupu w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> K_10
        {
            get
            {
                if (this.K_10ValueSpecified)
                {
                    return this.K_10Value;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.K_10Value = value.GetValueOrDefault();
                this.K_10ValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Koszty uboczne zakupu w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Koszty uboczne zakupu w PLN")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("K_11")]
        public decimal K_11Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the K_11 property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool K_11ValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Koszty uboczne zakupu w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> K_11
        {
            get
            {
                if (this.K_11ValueSpecified)
                {
                    return this.K_11Value;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.K_11Value = value.GetValueOrDefault();
                this.K_11ValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Wydatki (koszty) - wynagrodzenia w gotówce i w naturze w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Wydatki (koszty) - wynagrodzenia w gotówce i w naturze w PLN")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("K_12")]
        public decimal K_12Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the K_12 property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool K_12ValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Wydatki (koszty) - wynagrodzenia w gotówce i w naturze w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> K_12
        {
            get
            {
                if (this.K_12ValueSpecified)
                {
                    return this.K_12Value;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.K_12Value = value.GetValueOrDefault();
                this.K_12ValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Wydatki (koszty) - pozostałe wydatki w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Wydatki (koszty) - pozostałe wydatki w PLN")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("K_13")]
        public decimal K_13Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the K_13 property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool K_13ValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Wydatki (koszty) - pozostałe wydatki w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> K_13
        {
            get
            {
                if (this.K_13ValueSpecified)
                {
                    return this.K_13Value;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.K_13Value = value.GetValueOrDefault();
                this.K_13ValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Wydatki (koszty) - razem wydatki (12+13) w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Wydatki (koszty) - razem wydatki (12+13) w PLN")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("K_14")]
        public decimal K_14Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the K_14 property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool K_14ValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Wydatki (koszty) - razem wydatki (12+13) w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> K_14
        {
            get
            {
                if (this.K_14ValueSpecified)
                {
                    return this.K_14Value;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.K_14Value = value.GetValueOrDefault();
                this.K_14ValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Wydatki (koszty) dla rolników prowadzących działalność gospodarczą w PLN (§ 2 ust. 2 rozporządzenia)</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Wydatki (koszty) dla rolników prowadzących działalność gospodarczą w PLN (§ 2 ust" +
            ". 2 rozporządzenia)")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("K_14A")]
        public decimal K_14AValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the K_14A property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool K_14AValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Wydatki (koszty) dla rolników prowadzących działalność gospodarczą w PLN (§ 2 ust. 2 rozporządzenia)</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> K_14A
        {
            get
            {
                if (this.K_14AValueSpecified)
                {
                    return this.K_14AValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.K_14AValue = value.GetValueOrDefault();
                this.K_14AValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Wydatki (koszty) - pole wolne w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Wydatki (koszty) - pole wolne w PLN")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("K_15")]
        public decimal K_15Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the K_15 property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool K_15ValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Wydatki (koszty) - pole wolne w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> K_15
        {
            get
            {
                if (this.K_15ValueSpecified)
                {
                    return this.K_15Value;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.K_15Value = value.GetValueOrDefault();
                this.K_15ValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Koszty działalności badawczo-rozwojowej, o których mowa w art. 26e ustawy o podatku dochodowym - opis kosztu</para>
        /// <para>Typ znakowy ograniczony do 256 znaków</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Koszty działalności badawczo-rozwojowej, o których mowa w art. 26e ustawy o podat" +
            "ku dochodowym - opis kosztu")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.Xml.Serialization.XmlElementAttribute("K_16A")]
        public string K_16A { get; set; }
        
        /// <summary>
        /// <para>Koszty działalności badawczo-rozwojowej, o których mowa w art. 26e ustawy o podatku dochodowym - wartość w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Koszty działalności badawczo-rozwojowej, o których mowa w art. 26e ustawy o podat" +
            "ku dochodowym - wartość w PLN")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("K_16B")]
        public decimal K_16BValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the K_16B property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool K_16BValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Koszty działalności badawczo-rozwojowej, o których mowa w art. 26e ustawy o podatku dochodowym - wartość w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> K_16B
        {
            get
            {
                if (this.K_16BValueSpecified)
                {
                    return this.K_16BValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.K_16BValue = value.GetValueOrDefault();
                this.K_16BValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Uwagi</para>
        /// <para>Typ znakowy ograniczony do 256 znaków</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Uwagi")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.Xml.Serialization.XmlElementAttribute("K_17")]
        public string K_17 { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JPKPKPIRCtrl", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JPKPKPIRCtrl
    {
        
        /// <summary>
        /// <para>Liczba wierszy (zapisów) PKPIR, w okresie którego dotyczy JPK_PKPIR</para>
        /// <para>Liczby naturalne większe od zera</para>
        /// <para xml:lang="en">Total number of digits: 14.</para>
        /// <para xml:lang="en">Minimum exclusive value: 0.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Liczba wierszy (zapisów) PKPIR, w okresie którego dotyczy JPK_PKPIR")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("LiczbaWierszy")]
        public ulong LiczbaWierszy { get; set; }
        
        /// <summary>
        /// <para>Łączna wartość przychodów razem (kol. K_9) w PKPIR, w okresie którego dotyczy JPK_PKPIR</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Łączna wartość przychodów razem (kol. K_9) w PKPIR, w okresie którego dotyczy JPK" +
            "_PKPIR")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("SumaPrzychodow")]
        public decimal SumaPrzychodow { get; set; }
        
        /// <summary>
        /// <para>Łączna wartość przychodów razem (kol. K_9A) w PKPIR, w okresie którego dotyczy JPK_PKPIR</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Łączna wartość przychodów razem (kol. K_9A) w PKPIR, w okresie którego dotyczy JP" +
            "K_PKPIR")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("SumaPrzychodow2")]
        public decimal SumaPrzychodow2Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SumaPrzychodow2 property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SumaPrzychodow2ValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Łączna wartość przychodów razem (kol. K_9A) w PKPIR, w okresie którego dotyczy JPK_PKPIR</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> SumaPrzychodow2
        {
            get
            {
                if (this.SumaPrzychodow2ValueSpecified)
                {
                    return this.SumaPrzychodow2Value;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SumaPrzychodow2Value = value.GetValueOrDefault();
                this.SumaPrzychodow2ValueSpecified = value.HasValue;
            }
        }
    }
