//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ProFak.IO.JPK_PKPIR {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/", IsNullable=false)]
    public partial class JPK {
        
        private TNaglowek naglowekField;
        
        private JPKPodmiot1 podmiot1Field;
        
        private JPKPKPIRInfo pKPIRInfoField;
        
        private JPKPKPIRSpis[] pKPIRSpisField;
        
        private JPKPKPIRWiersz[] pKPIRWierszField;
        
        private JPKPKPIRCtrl pKPIRCtrlField;
        
        /// <remarks/>
        public TNaglowek Naglowek {
            get {
                return this.naglowekField;
            }
            set {
                this.naglowekField = value;
            }
        }
        
        /// <remarks/>
        public JPKPodmiot1 Podmiot1 {
            get {
                return this.podmiot1Field;
            }
            set {
                this.podmiot1Field = value;
            }
        }
        
        /// <remarks/>
        public JPKPKPIRInfo PKPIRInfo {
            get {
                return this.pKPIRInfoField;
            }
            set {
                this.pKPIRInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PKPIRSpis")]
        public JPKPKPIRSpis[] PKPIRSpis {
            get {
                return this.pKPIRSpisField;
            }
            set {
                this.pKPIRSpisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PKPIRWiersz")]
        public JPKPKPIRWiersz[] PKPIRWiersz {
            get {
                return this.pKPIRWierszField;
            }
            set {
                this.pKPIRWierszField = value;
            }
        }
        
        /// <remarks/>
        public JPKPKPIRCtrl PKPIRCtrl {
            get {
                return this.pKPIRCtrlField;
            }
            set {
                this.pKPIRCtrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    public partial class TNaglowek {
        
        private TNaglowekKodFormularza kodFormularzaField;
        
        private sbyte wariantFormularzaField;
        
        private sbyte celZlozeniaField;
        
        private System.DateTime dataWytworzeniaJPKField;
        
        private System.DateTime dataOdField;
        
        private System.DateTime dataDoField;
        
        private TKodUS kodUrzeduField;
        
        /// <remarks/>
        public TNaglowekKodFormularza KodFormularza {
            get {
                return this.kodFormularzaField;
            }
            set {
                this.kodFormularzaField = value;
            }
        }
        
        /// <remarks/>
        public sbyte WariantFormularza {
            get {
                return this.wariantFormularzaField;
            }
            set {
                this.wariantFormularzaField = value;
            }
        }
        
        /// <remarks/>
        public sbyte CelZlozenia {
            get {
                return this.celZlozeniaField;
            }
            set {
                this.celZlozeniaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataWytworzeniaJPK {
            get {
                return this.dataWytworzeniaJPKField;
            }
            set {
                this.dataWytworzeniaJPKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataOd {
            get {
                return this.dataOdField;
            }
            set {
                this.dataOdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataDo {
            get {
                return this.dataDoField;
            }
            set {
                this.dataDoField = value;
            }
        }
        
        /// <remarks/>
        public TKodUS KodUrzedu {
            get {
                return this.kodUrzeduField;
            }
            set {
                this.kodUrzeduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    public partial class TNaglowekKodFormularza {
        
        private string kodSystemowyField;
        
        private string wersjaSchemyField;
        
        private TKodFormularza valueField;
        
        public TNaglowekKodFormularza() {
            this.kodSystemowyField = "JPK_PKPIR (3)";
            this.wersjaSchemyField = "1-0";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string kodSystemowy {
            get {
                return this.kodSystemowyField;
            }
            set {
                this.kodSystemowyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string wersjaSchemy {
            get {
                return this.wersjaSchemyField;
            }
            set {
                this.wersjaSchemyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public TKodFormularza Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    public enum TKodFormularza {
        
        /// <remarks/>
        JPK_PKPIR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    public partial class TIdentyfikatorOsobyNiefizycznej {
        
        private string nIPField;
        
        private string pelnaNazwaField;
        
        /// <remarks/>
        public string NIP {
            get {
                return this.nIPField;
            }
            set {
                this.nIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string PelnaNazwa {
            get {
                return this.pelnaNazwaField;
            }
            set {
                this.pelnaNazwaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/")]
    public partial class TIdentyfikatorOsobyFizycznej2 {
        
        private string nIPField;
        
        private string imiePierwszeField;
        
        private string nazwiskoField;
        
        private System.DateTime dataUrodzeniaField;
        
        /// <remarks/>
        public string NIP {
            get {
                return this.nIPField;
            }
            set {
                this.nIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string ImiePierwsze {
            get {
                return this.imiePierwszeField;
            }
            set {
                this.imiePierwszeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string Nazwisko {
            get {
                return this.nazwiskoField;
            }
            set {
                this.nazwiskoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataUrodzenia {
            get {
                return this.dataUrodzeniaField;
            }
            set {
                this.dataUrodzeniaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    public partial class TPodmiotDowolnyBezAdresu {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OsobaFizyczna", typeof(TPodmiotDowolnyBezAdresuOsobaFizyczna))]
        [System.Xml.Serialization.XmlElementAttribute("OsobaNiefizyczna", typeof(TPodmiotDowolnyBezAdresuOsobaNiefizyczna))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    public partial class TPodmiotDowolnyBezAdresuOsobaFizyczna : TIdentyfikatorOsobyFizycznej2 {
        
        private string emailField;
        
        private string telefonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string Telefon {
            get {
                return this.telefonField;
            }
            set {
                this.telefonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    public partial class TPodmiotDowolnyBezAdresuOsobaNiefizyczna : TIdentyfikatorOsobyNiefizycznej {
        
        private string emailField;
        
        private string telefonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string Telefon {
            get {
                return this.telefonField;
            }
            set {
                this.telefonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/KodyUrzedowSkarbowych" +
        "/")]
    public enum TKodUS {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0202")]
        Item0202,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0203")]
        Item0203,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0204")]
        Item0204,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0205")]
        Item0205,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0206")]
        Item0206,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0207")]
        Item0207,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0208")]
        Item0208,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0209")]
        Item0209,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0210")]
        Item0210,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0211")]
        Item0211,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0212")]
        Item0212,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0213")]
        Item0213,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0214")]
        Item0214,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0215")]
        Item0215,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0216")]
        Item0216,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0217")]
        Item0217,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0218")]
        Item0218,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0219")]
        Item0219,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0220")]
        Item0220,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0221")]
        Item0221,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0222")]
        Item0222,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0223")]
        Item0223,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0224")]
        Item0224,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0225")]
        Item0225,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0226")]
        Item0226,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0227")]
        Item0227,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0228")]
        Item0228,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0229")]
        Item0229,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0230")]
        Item0230,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0231")]
        Item0231,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0232")]
        Item0232,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0233")]
        Item0233,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0234")]
        Item0234,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0271")]
        Item0271,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0402")]
        Item0402,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0403")]
        Item0403,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0404")]
        Item0404,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0405")]
        Item0405,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0406")]
        Item0406,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0407")]
        Item0407,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0408")]
        Item0408,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0409")]
        Item0409,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0410")]
        Item0410,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0411")]
        Item0411,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0412")]
        Item0412,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0413")]
        Item0413,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0414")]
        Item0414,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0415")]
        Item0415,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0416")]
        Item0416,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0417")]
        Item0417,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0418")]
        Item0418,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0419")]
        Item0419,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0420")]
        Item0420,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0421")]
        Item0421,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0422")]
        Item0422,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0423")]
        Item0423,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0471")]
        Item0471,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0602")]
        Item0602,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0603")]
        Item0603,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0604")]
        Item0604,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0605")]
        Item0605,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0606")]
        Item0606,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0607")]
        Item0607,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0608")]
        Item0608,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0609")]
        Item0609,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0610")]
        Item0610,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0611")]
        Item0611,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0612")]
        Item0612,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0613")]
        Item0613,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0614")]
        Item0614,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0615")]
        Item0615,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0616")]
        Item0616,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0617")]
        Item0617,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0618")]
        Item0618,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0619")]
        Item0619,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0620")]
        Item0620,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0621")]
        Item0621,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0622")]
        Item0622,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0671")]
        Item0671,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0802")]
        Item0802,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0803")]
        Item0803,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0804")]
        Item0804,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0805")]
        Item0805,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0806")]
        Item0806,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0807")]
        Item0807,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0808")]
        Item0808,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0809")]
        Item0809,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0810")]
        Item0810,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0811")]
        Item0811,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0812")]
        Item0812,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0813")]
        Item0813,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0814")]
        Item0814,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0871")]
        Item0871,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1002")]
        Item1002,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1003")]
        Item1003,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1004")]
        Item1004,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1005")]
        Item1005,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1006")]
        Item1006,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1007")]
        Item1007,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1008")]
        Item1008,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1009")]
        Item1009,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1010")]
        Item1010,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1011")]
        Item1011,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1012")]
        Item1012,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1013")]
        Item1013,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1014")]
        Item1014,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1015")]
        Item1015,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1016")]
        Item1016,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1017")]
        Item1017,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1018")]
        Item1018,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1019")]
        Item1019,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1020")]
        Item1020,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1021")]
        Item1021,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1022")]
        Item1022,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1023")]
        Item1023,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1024")]
        Item1024,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1025")]
        Item1025,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1026")]
        Item1026,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1027")]
        Item1027,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1028")]
        Item1028,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1029")]
        Item1029,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1071")]
        Item1071,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1202")]
        Item1202,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1203")]
        Item1203,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1204")]
        Item1204,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1205")]
        Item1205,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1206")]
        Item1206,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1207")]
        Item1207,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1208")]
        Item1208,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1209")]
        Item1209,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1210")]
        Item1210,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1211")]
        Item1211,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1212")]
        Item1212,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1213")]
        Item1213,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1214")]
        Item1214,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1215")]
        Item1215,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1216")]
        Item1216,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1217")]
        Item1217,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1218")]
        Item1218,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1219")]
        Item1219,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1220")]
        Item1220,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1221")]
        Item1221,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1222")]
        Item1222,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1223")]
        Item1223,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1224")]
        Item1224,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1225")]
        Item1225,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1226")]
        Item1226,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1227")]
        Item1227,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1228")]
        Item1228,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1271")]
        Item1271,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1402")]
        Item1402,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1403")]
        Item1403,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1404")]
        Item1404,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1405")]
        Item1405,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1406")]
        Item1406,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1407")]
        Item1407,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1408")]
        Item1408,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1409")]
        Item1409,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1410")]
        Item1410,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1411")]
        Item1411,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1412")]
        Item1412,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1413")]
        Item1413,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1414")]
        Item1414,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1415")]
        Item1415,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1416")]
        Item1416,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1417")]
        Item1417,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1418")]
        Item1418,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1419")]
        Item1419,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1420")]
        Item1420,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1421")]
        Item1421,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1422")]
        Item1422,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1423")]
        Item1423,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1424")]
        Item1424,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1425")]
        Item1425,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1426")]
        Item1426,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1427")]
        Item1427,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1428")]
        Item1428,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1429")]
        Item1429,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1430")]
        Item1430,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1431")]
        Item1431,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1432")]
        Item1432,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1433")]
        Item1433,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1434")]
        Item1434,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1435")]
        Item1435,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1436")]
        Item1436,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1437")]
        Item1437,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1438")]
        Item1438,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1439")]
        Item1439,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1440")]
        Item1440,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1441")]
        Item1441,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1442")]
        Item1442,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1443")]
        Item1443,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1444")]
        Item1444,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1445")]
        Item1445,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1446")]
        Item1446,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1447")]
        Item1447,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1448")]
        Item1448,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1449")]
        Item1449,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1471")]
        Item1471,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1472")]
        Item1472,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1473")]
        Item1473,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1602")]
        Item1602,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1603")]
        Item1603,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1604")]
        Item1604,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1605")]
        Item1605,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1606")]
        Item1606,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1607")]
        Item1607,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1608")]
        Item1608,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1609")]
        Item1609,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1610")]
        Item1610,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1611")]
        Item1611,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1612")]
        Item1612,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1613")]
        Item1613,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1671")]
        Item1671,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1802")]
        Item1802,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1803")]
        Item1803,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1804")]
        Item1804,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1805")]
        Item1805,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1806")]
        Item1806,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1807")]
        Item1807,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1808")]
        Item1808,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1809")]
        Item1809,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1810")]
        Item1810,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1811")]
        Item1811,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1812")]
        Item1812,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1813")]
        Item1813,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1814")]
        Item1814,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1815")]
        Item1815,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1816")]
        Item1816,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1817")]
        Item1817,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1818")]
        Item1818,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1819")]
        Item1819,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1820")]
        Item1820,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1821")]
        Item1821,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1822")]
        Item1822,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1823")]
        Item1823,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1871")]
        Item1871,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2002")]
        Item2002,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2003")]
        Item2003,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2004")]
        Item2004,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2005")]
        Item2005,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2006")]
        Item2006,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2007")]
        Item2007,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2008")]
        Item2008,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2009")]
        Item2009,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2010")]
        Item2010,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2011")]
        Item2011,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2012")]
        Item2012,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2013")]
        Item2013,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2014")]
        Item2014,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2015")]
        Item2015,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2071")]
        Item2071,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2202")]
        Item2202,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2203")]
        Item2203,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2204")]
        Item2204,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2205")]
        Item2205,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2206")]
        Item2206,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2207")]
        Item2207,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2208")]
        Item2208,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2209")]
        Item2209,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2210")]
        Item2210,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2211")]
        Item2211,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2212")]
        Item2212,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2213")]
        Item2213,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2214")]
        Item2214,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2215")]
        Item2215,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2216")]
        Item2216,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2217")]
        Item2217,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2218")]
        Item2218,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2219")]
        Item2219,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2220")]
        Item2220,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2221")]
        Item2221,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2271")]
        Item2271,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2402")]
        Item2402,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2403")]
        Item2403,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2404")]
        Item2404,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2405")]
        Item2405,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2406")]
        Item2406,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2407")]
        Item2407,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2408")]
        Item2408,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2409")]
        Item2409,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2410")]
        Item2410,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2411")]
        Item2411,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2412")]
        Item2412,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2413")]
        Item2413,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2414")]
        Item2414,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2415")]
        Item2415,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2416")]
        Item2416,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2417")]
        Item2417,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2418")]
        Item2418,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2419")]
        Item2419,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2420")]
        Item2420,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2421")]
        Item2421,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2422")]
        Item2422,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2423")]
        Item2423,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2424")]
        Item2424,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2425")]
        Item2425,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2426")]
        Item2426,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2427")]
        Item2427,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2428")]
        Item2428,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2429")]
        Item2429,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2430")]
        Item2430,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2431")]
        Item2431,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2432")]
        Item2432,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2433")]
        Item2433,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2434")]
        Item2434,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2435")]
        Item2435,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2436")]
        Item2436,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2471")]
        Item2471,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2472")]
        Item2472,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2602")]
        Item2602,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2603")]
        Item2603,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2604")]
        Item2604,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2605")]
        Item2605,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2606")]
        Item2606,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2607")]
        Item2607,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2608")]
        Item2608,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2609")]
        Item2609,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2610")]
        Item2610,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2611")]
        Item2611,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2612")]
        Item2612,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2613")]
        Item2613,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2614")]
        Item2614,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2615")]
        Item2615,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2671")]
        Item2671,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2802")]
        Item2802,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2803")]
        Item2803,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2804")]
        Item2804,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2805")]
        Item2805,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2806")]
        Item2806,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2807")]
        Item2807,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2808")]
        Item2808,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2809")]
        Item2809,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2810")]
        Item2810,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2811")]
        Item2811,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2812")]
        Item2812,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2813")]
        Item2813,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2814")]
        Item2814,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2815")]
        Item2815,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2816")]
        Item2816,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2871")]
        Item2871,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3002")]
        Item3002,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3003")]
        Item3003,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3004")]
        Item3004,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3005")]
        Item3005,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3006")]
        Item3006,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3007")]
        Item3007,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3008")]
        Item3008,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3009")]
        Item3009,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3010")]
        Item3010,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3011")]
        Item3011,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3012")]
        Item3012,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3013")]
        Item3013,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3014")]
        Item3014,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3015")]
        Item3015,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3016")]
        Item3016,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3017")]
        Item3017,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3018")]
        Item3018,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3019")]
        Item3019,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3020")]
        Item3020,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3021")]
        Item3021,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3022")]
        Item3022,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3023")]
        Item3023,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3025")]
        Item3025,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3026")]
        Item3026,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3027")]
        Item3027,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3028")]
        Item3028,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3029")]
        Item3029,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3030")]
        Item3030,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3031")]
        Item3031,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3032")]
        Item3032,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3033")]
        Item3033,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3034")]
        Item3034,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3035")]
        Item3035,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3036")]
        Item3036,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3037")]
        Item3037,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3038")]
        Item3038,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3039")]
        Item3039,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3071")]
        Item3071,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3072")]
        Item3072,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3202")]
        Item3202,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3203")]
        Item3203,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3204")]
        Item3204,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3205")]
        Item3205,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3206")]
        Item3206,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3207")]
        Item3207,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3208")]
        Item3208,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3209")]
        Item3209,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3210")]
        Item3210,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3211")]
        Item3211,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3212")]
        Item3212,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3213")]
        Item3213,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3214")]
        Item3214,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3215")]
        Item3215,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3216")]
        Item3216,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3217")]
        Item3217,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3218")]
        Item3218,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3219")]
        Item3219,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3220")]
        Item3220,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3271")]
        Item3271,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    public partial class JPKPodmiot1 : TPodmiotDowolnyBezAdresu {
        
        private sbyte kasowy_PITField;
        
        private bool kasowy_PITFieldSpecified;
        
        private sbyte rolnik_PITField;
        
        private bool rolnik_PITFieldSpecified;
        
        private string rolaField;
        
        public JPKPodmiot1() {
            this.rolaField = "Podatnik";
        }
        
        /// <remarks/>
        public sbyte Kasowy_PIT {
            get {
                return this.kasowy_PITField;
            }
            set {
                this.kasowy_PITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Kasowy_PITSpecified {
            get {
                return this.kasowy_PITFieldSpecified;
            }
            set {
                this.kasowy_PITFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public sbyte Rolnik_PIT {
            get {
                return this.rolnik_PITField;
            }
            set {
                this.rolnik_PITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Rolnik_PITSpecified {
            get {
                return this.rolnik_PITFieldSpecified;
            }
            set {
                this.rolnik_PITFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rola {
            get {
                return this.rolaField;
            }
            set {
                this.rolaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    public partial class JPKPKPIRInfo {
        
        private decimal p_1Field;
        
        private decimal p_2Field;
        
        private decimal p_3Field;
        
        private decimal p_4Field;
        
        /// <remarks/>
        public decimal P_1 {
            get {
                return this.p_1Field;
            }
            set {
                this.p_1Field = value;
            }
        }
        
        /// <remarks/>
        public decimal P_2 {
            get {
                return this.p_2Field;
            }
            set {
                this.p_2Field = value;
            }
        }
        
        /// <remarks/>
        public decimal P_3 {
            get {
                return this.p_3Field;
            }
            set {
                this.p_3Field = value;
            }
        }
        
        /// <remarks/>
        public decimal P_4 {
            get {
                return this.p_4Field;
            }
            set {
                this.p_4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    public partial class JPKPKPIRSpis {
        
        private System.DateTime p_5AField;
        
        private decimal p_5BField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime P_5A {
            get {
                return this.p_5AField;
            }
            set {
                this.p_5AField = value;
            }
        }
        
        /// <remarks/>
        public decimal P_5B {
            get {
                return this.p_5BField;
            }
            set {
                this.p_5BField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    public partial class JPKPKPIRWiersz {
        
        private string k_1Field;
        
        private System.DateTime k_2Field;
        
        private string k_3AField;
        
        private string k_3BField;
        
        private TKodKraju k_4AField;
        
        private bool k_4AFieldSpecified;
        
        private string k_4BField;
        
        private string k_5AField;
        
        private string k_5BField;
        
        private string k_6Field;
        
        private decimal k_7Field;
        
        private bool k_7FieldSpecified;
        
        private decimal k_8Field;
        
        private bool k_8FieldSpecified;
        
        private decimal k_9Field;
        
        private bool k_9FieldSpecified;
        
        private decimal k_9AField;
        
        private bool k_9AFieldSpecified;
        
        private decimal k_10Field;
        
        private bool k_10FieldSpecified;
        
        private decimal k_11Field;
        
        private bool k_11FieldSpecified;
        
        private decimal k_12Field;
        
        private bool k_12FieldSpecified;
        
        private decimal k_13Field;
        
        private bool k_13FieldSpecified;
        
        private decimal k_14Field;
        
        private bool k_14FieldSpecified;
        
        private decimal k_14AField;
        
        private bool k_14AFieldSpecified;
        
        private decimal k_15Field;
        
        private bool k_15FieldSpecified;
        
        private string k_16AField;
        
        private decimal k_16BField;
        
        private string k_17Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string K_1 {
            get {
                return this.k_1Field;
            }
            set {
                this.k_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime K_2 {
            get {
                return this.k_2Field;
            }
            set {
                this.k_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string K_3A {
            get {
                return this.k_3AField;
            }
            set {
                this.k_3AField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string K_3B {
            get {
                return this.k_3BField;
            }
            set {
                this.k_3BField = value;
            }
        }
        
        /// <remarks/>
        public TKodKraju K_4A {
            get {
                return this.k_4AField;
            }
            set {
                this.k_4AField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_4ASpecified {
            get {
                return this.k_4AFieldSpecified;
            }
            set {
                this.k_4AFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string K_4B {
            get {
                return this.k_4BField;
            }
            set {
                this.k_4BField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string K_5A {
            get {
                return this.k_5AField;
            }
            set {
                this.k_5AField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string K_5B {
            get {
                return this.k_5BField;
            }
            set {
                this.k_5BField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string K_6 {
            get {
                return this.k_6Field;
            }
            set {
                this.k_6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal K_7 {
            get {
                return this.k_7Field;
            }
            set {
                this.k_7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_7Specified {
            get {
                return this.k_7FieldSpecified;
            }
            set {
                this.k_7FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal K_8 {
            get {
                return this.k_8Field;
            }
            set {
                this.k_8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_8Specified {
            get {
                return this.k_8FieldSpecified;
            }
            set {
                this.k_8FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal K_9 {
            get {
                return this.k_9Field;
            }
            set {
                this.k_9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_9Specified {
            get {
                return this.k_9FieldSpecified;
            }
            set {
                this.k_9FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal K_9A {
            get {
                return this.k_9AField;
            }
            set {
                this.k_9AField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_9ASpecified {
            get {
                return this.k_9AFieldSpecified;
            }
            set {
                this.k_9AFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal K_10 {
            get {
                return this.k_10Field;
            }
            set {
                this.k_10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_10Specified {
            get {
                return this.k_10FieldSpecified;
            }
            set {
                this.k_10FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal K_11 {
            get {
                return this.k_11Field;
            }
            set {
                this.k_11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_11Specified {
            get {
                return this.k_11FieldSpecified;
            }
            set {
                this.k_11FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal K_12 {
            get {
                return this.k_12Field;
            }
            set {
                this.k_12Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_12Specified {
            get {
                return this.k_12FieldSpecified;
            }
            set {
                this.k_12FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal K_13 {
            get {
                return this.k_13Field;
            }
            set {
                this.k_13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_13Specified {
            get {
                return this.k_13FieldSpecified;
            }
            set {
                this.k_13FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal K_14 {
            get {
                return this.k_14Field;
            }
            set {
                this.k_14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_14Specified {
            get {
                return this.k_14FieldSpecified;
            }
            set {
                this.k_14FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal K_14A {
            get {
                return this.k_14AField;
            }
            set {
                this.k_14AField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_14ASpecified {
            get {
                return this.k_14AFieldSpecified;
            }
            set {
                this.k_14AFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal K_15 {
            get {
                return this.k_15Field;
            }
            set {
                this.k_15Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_15Specified {
            get {
                return this.k_15FieldSpecified;
            }
            set {
                this.k_15FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string K_16A {
            get {
                return this.k_16AField;
            }
            set {
                this.k_16AField = value;
            }
        }
        
        /// <remarks/>
        public decimal K_16B {
            get {
                return this.k_16BField;
            }
            set {
                this.k_16BField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string K_17 {
            get {
                return this.k_17Field;
            }
            set {
                this.k_17Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/")]
    public enum TKodKraju {
        
        /// <remarks/>
        AF,
        
        /// <remarks/>
        AX,
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        DZ,
        
        /// <remarks/>
        AD,
        
        /// <remarks/>
        AO,
        
        /// <remarks/>
        AI,
        
        /// <remarks/>
        AQ,
        
        /// <remarks/>
        AG,
        
        /// <remarks/>
        AN,
        
        /// <remarks/>
        SA,
        
        /// <remarks/>
        AR,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        AW,
        
        /// <remarks/>
        AU,
        
        /// <remarks/>
        AT,
        
        /// <remarks/>
        AZ,
        
        /// <remarks/>
        BS,
        
        /// <remarks/>
        BH,
        
        /// <remarks/>
        BD,
        
        /// <remarks/>
        BB,
        
        /// <remarks/>
        BE,
        
        /// <remarks/>
        BZ,
        
        /// <remarks/>
        BJ,
        
        /// <remarks/>
        BM,
        
        /// <remarks/>
        BT,
        
        /// <remarks/>
        BY,
        
        /// <remarks/>
        BO,
        
        /// <remarks/>
        BQ,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        BW,
        
        /// <remarks/>
        BR,
        
        /// <remarks/>
        BN,
        
        /// <remarks/>
        IO,
        
        /// <remarks/>
        BG,
        
        /// <remarks/>
        BF,
        
        /// <remarks/>
        BI,
        
        /// <remarks/>
        XC,
        
        /// <remarks/>
        CL,
        
        /// <remarks/>
        CN,
        
        /// <remarks/>
        HR,
        
        /// <remarks/>
        CW,
        
        /// <remarks/>
        CY,
        
        /// <remarks/>
        TD,
        
        /// <remarks/>
        ME,
        
        /// <remarks/>
        DK,
        
        /// <remarks/>
        DM,
        
        /// <remarks/>
        DO,
        
        /// <remarks/>
        DJ,
        
        /// <remarks/>
        EG,
        
        /// <remarks/>
        EC,
        
        /// <remarks/>
        ER,
        
        /// <remarks/>
        EE,
        
        /// <remarks/>
        ET,
        
        /// <remarks/>
        FK,
        
        /// <remarks/>
        FJ,
        
        /// <remarks/>
        PH,
        
        /// <remarks/>
        FI,
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        TF,
        
        /// <remarks/>
        GA,
        
        /// <remarks/>
        GM,
        
        /// <remarks/>
        GH,
        
        /// <remarks/>
        GI,
        
        /// <remarks/>
        GR,
        
        /// <remarks/>
        GD,
        
        /// <remarks/>
        GL,
        
        /// <remarks/>
        GE,
        
        /// <remarks/>
        GU,
        
        /// <remarks/>
        GG,
        
        /// <remarks/>
        GY,
        
        /// <remarks/>
        GF,
        
        /// <remarks/>
        GP,
        
        /// <remarks/>
        GT,
        
        /// <remarks/>
        GN,
        
        /// <remarks/>
        GQ,
        
        /// <remarks/>
        GW,
        
        /// <remarks/>
        HT,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        HN,
        
        /// <remarks/>
        HK,
        
        /// <remarks/>
        IN,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        IQ,
        
        /// <remarks/>
        IR,
        
        /// <remarks/>
        IE,
        
        /// <remarks/>
        IS,
        
        /// <remarks/>
        IL,
        
        /// <remarks/>
        JM,
        
        /// <remarks/>
        JP,
        
        /// <remarks/>
        YE,
        
        /// <remarks/>
        JE,
        
        /// <remarks/>
        JO,
        
        /// <remarks/>
        KY,
        
        /// <remarks/>
        KH,
        
        /// <remarks/>
        CM,
        
        /// <remarks/>
        CA,
        
        /// <remarks/>
        QA,
        
        /// <remarks/>
        KZ,
        
        /// <remarks/>
        KE,
        
        /// <remarks/>
        KG,
        
        /// <remarks/>
        KI,
        
        /// <remarks/>
        CO,
        
        /// <remarks/>
        KM,
        
        /// <remarks/>
        CG,
        
        /// <remarks/>
        CD,
        
        /// <remarks/>
        KP,
        
        /// <remarks/>
        XK,
        
        /// <remarks/>
        CR,
        
        /// <remarks/>
        CU,
        
        /// <remarks/>
        KW,
        
        /// <remarks/>
        LA,
        
        /// <remarks/>
        LS,
        
        /// <remarks/>
        LB,
        
        /// <remarks/>
        LR,
        
        /// <remarks/>
        LY,
        
        /// <remarks/>
        LI,
        
        /// <remarks/>
        LT,
        
        /// <remarks/>
        LV,
        
        /// <remarks/>
        LU,
        
        /// <remarks/>
        MK,
        
        /// <remarks/>
        MG,
        
        /// <remarks/>
        YT,
        
        /// <remarks/>
        MO,
        
        /// <remarks/>
        MW,
        
        /// <remarks/>
        MV,
        
        /// <remarks/>
        MY,
        
        /// <remarks/>
        ML,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        MP,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        MQ,
        
        /// <remarks/>
        MR,
        
        /// <remarks/>
        MU,
        
        /// <remarks/>
        MX,
        
        /// <remarks/>
        XL,
        
        /// <remarks/>
        FM,
        
        /// <remarks/>
        UM,
        
        /// <remarks/>
        MD,
        
        /// <remarks/>
        MC,
        
        /// <remarks/>
        MN,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MZ,
        
        /// <remarks/>
        MM,
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        NR,
        
        /// <remarks/>
        NP,
        
        /// <remarks/>
        NL,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        NG,
        
        /// <remarks/>
        NI,
        
        /// <remarks/>
        NU,
        
        /// <remarks/>
        NF,
        
        /// <remarks/>
        NO,
        
        /// <remarks/>
        NC,
        
        /// <remarks/>
        NZ,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        OM,
        
        /// <remarks/>
        PK,
        
        /// <remarks/>
        PW,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PG,
        
        /// <remarks/>
        PY,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        PN,
        
        /// <remarks/>
        PF,
        
        /// <remarks/>
        PL,
        
        /// <remarks/>
        GS,
        
        /// <remarks/>
        PT,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        CF,
        
        /// <remarks/>
        CZ,
        
        /// <remarks/>
        KR,
        
        /// <remarks/>
        ZA,
        
        /// <remarks/>
        RE,
        
        /// <remarks/>
        RU,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        RW,
        
        /// <remarks/>
        EH,
        
        /// <remarks/>
        BL,
        
        /// <remarks/>
        KN,
        
        /// <remarks/>
        LC,
        
        /// <remarks/>
        MF,
        
        /// <remarks/>
        VC,
        
        /// <remarks/>
        SV,
        
        /// <remarks/>
        WS,
        
        /// <remarks/>
        AS,
        
        /// <remarks/>
        SM,
        
        /// <remarks/>
        SN,
        
        /// <remarks/>
        RS,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        SL,
        
        /// <remarks/>
        SG,
        
        /// <remarks/>
        SK,
        
        /// <remarks/>
        SI,
        
        /// <remarks/>
        SO,
        
        /// <remarks/>
        LK,
        
        /// <remarks/>
        PM,
        
        /// <remarks/>
        US,
        
        /// <remarks/>
        SZ,
        
        /// <remarks/>
        SD,
        
        /// <remarks/>
        SS,
        
        /// <remarks/>
        SR,
        
        /// <remarks/>
        SJ,
        
        /// <remarks/>
        SH,
        
        /// <remarks/>
        SY,
        
        /// <remarks/>
        CH,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        TJ,
        
        /// <remarks/>
        TH,
        
        /// <remarks/>
        TW,
        
        /// <remarks/>
        TZ,
        
        /// <remarks/>
        TG,
        
        /// <remarks/>
        TK,
        
        /// <remarks/>
        TO,
        
        /// <remarks/>
        TT,
        
        /// <remarks/>
        TN,
        
        /// <remarks/>
        TR,
        
        /// <remarks/>
        TM,
        
        /// <remarks/>
        TV,
        
        /// <remarks/>
        UG,
        
        /// <remarks/>
        UA,
        
        /// <remarks/>
        UY,
        
        /// <remarks/>
        UZ,
        
        /// <remarks/>
        VU,
        
        /// <remarks/>
        WF,
        
        /// <remarks/>
        VA,
        
        /// <remarks/>
        HU,
        
        /// <remarks/>
        VE,
        
        /// <remarks/>
        GB,
        
        /// <remarks/>
        VN,
        
        /// <remarks/>
        IT,
        
        /// <remarks/>
        TL,
        
        /// <remarks/>
        CI,
        
        /// <remarks/>
        BV,
        
        /// <remarks/>
        CX,
        
        /// <remarks/>
        IM,
        
        /// <remarks/>
        SX,
        
        /// <remarks/>
        CK,
        
        /// <remarks/>
        VI,
        
        /// <remarks/>
        VG,
        
        /// <remarks/>
        HM,
        
        /// <remarks/>
        CC,
        
        /// <remarks/>
        MH,
        
        /// <remarks/>
        FO,
        
        /// <remarks/>
        SB,
        
        /// <remarks/>
        ST,
        
        /// <remarks/>
        TC,
        
        /// <remarks/>
        ZM,
        
        /// <remarks/>
        CV,
        
        /// <remarks/>
        ZW,
        
        /// <remarks/>
        AE,
        
        /// <remarks/>
        XI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10302/")]
    public partial class JPKPKPIRCtrl {
        
        private string liczbaWierszyField;
        
        private decimal sumaPrzychodowField;
        
        private decimal sumaPrzychodow2Field;
        
        private bool sumaPrzychodow2FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string LiczbaWierszy {
            get {
                return this.liczbaWierszyField;
            }
            set {
                this.liczbaWierszyField = value;
            }
        }
        
        /// <remarks/>
        public decimal SumaPrzychodow {
            get {
                return this.sumaPrzychodowField;
            }
            set {
                this.sumaPrzychodowField = value;
            }
        }
        
        /// <remarks/>
        public decimal SumaPrzychodow2 {
            get {
                return this.sumaPrzychodow2Field;
            }
            set {
                this.sumaPrzychodow2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SumaPrzychodow2Specified {
            get {
                return this.sumaPrzychodow2FieldSpecified;
            }
            set {
                this.sumaPrzychodow2FieldSpecified = value;
            }
        }
    }
}
