//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// XmlSchemaClassGenerator.Console --nullable --namespace http://crd.gov.pl/wzor/2025/12/19/14090/=ProFak.IO.JPK_V7M --namespace http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/=ProFak.IO.JPK_V7M.KodyKrajow --namespace http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/KodyUrzedowSkarbowych/=ProFak.IO.JPK_V7M.KodyUrzedowSkarbowych --namespace http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/=ProFak.IO.JPK_V7M.DefinicjeTypy --namingScheme=Direct http://crd.gov.pl/wzor/2025/12/19/14090/schemat.xsd
namespace ProFak.IO.JPK_V7M.KodyKrajow;

    
    
    /// <summary>
    /// <para>Słownik kodów krajów</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Słownik kodów krajów")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TKodKraju", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/")]
    [System.Xml.Serialization.XmlRootAttribute("TKodKraju", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/")]
    public enum TKodKraju
    {
        
        /// <summary>
        /// <para>AFGANISTAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("AFGANISTAN")]
        AF,
        
        /// <summary>
        /// <para>ALAND ISLANDS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ALAND ISLANDS")]
        AX,
        
        /// <summary>
        /// <para>ALBANIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ALBANIA")]
        AL,
        
        /// <summary>
        /// <para>ALGIERIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ALGIERIA")]
        DZ,
        
        /// <summary>
        /// <para>ANDORA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ANDORA")]
        AD,
        
        /// <summary>
        /// <para>ANGOLA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ANGOLA")]
        AO,
        
        /// <summary>
        /// <para>ANGUILLA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ANGUILLA")]
        AI,
        
        /// <summary>
        /// <para>ANTARKTYDA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ANTARKTYDA")]
        AQ,
        
        /// <summary>
        /// <para>ANTIGUA I BARBUDA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ANTIGUA I BARBUDA")]
        AG,
        
        /// <summary>
        /// <para>ANTYLE HOLENDERSKIE</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ANTYLE HOLENDERSKIE")]
        AN,
        
        /// <summary>
        /// <para>ARABIA SAUDYJSKA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ARABIA SAUDYJSKA")]
        SA,
        
        /// <summary>
        /// <para>ARGENTYNA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ARGENTYNA")]
        AR,
        
        /// <summary>
        /// <para>ARMENIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ARMENIA")]
        AM,
        
        /// <summary>
        /// <para>ARUBA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ARUBA")]
        AW,
        
        /// <summary>
        /// <para>AUSTRALIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("AUSTRALIA")]
        AU,
        
        /// <summary>
        /// <para>AUSTRIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("AUSTRIA")]
        AT,
        
        /// <summary>
        /// <para>AZERBEJDŻAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("AZERBEJDŻAN")]
        AZ,
        
        /// <summary>
        /// <para>BAHAMY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BAHAMY")]
        BS,
        
        /// <summary>
        /// <para>BAHRAJN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BAHRAJN")]
        BH,
        
        /// <summary>
        /// <para>BANGLADESZ</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BANGLADESZ")]
        BD,
        
        /// <summary>
        /// <para>BARBADOS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BARBADOS")]
        BB,
        
        /// <summary>
        /// <para>BELGIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BELGIA")]
        BE,
        
        /// <summary>
        /// <para>BELIZE</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BELIZE")]
        BZ,
        
        /// <summary>
        /// <para>BENIN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BENIN")]
        BJ,
        
        /// <summary>
        /// <para>BERMUDY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BERMUDY")]
        BM,
        
        /// <summary>
        /// <para>BHUTAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BHUTAN")]
        BT,
        
        /// <summary>
        /// <para>BIAŁORUŚ</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BIAŁORUŚ")]
        BY,
        
        /// <summary>
        /// <para>BOLIWIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BOLIWIA")]
        BO,
        
        /// <summary>
        /// <para>BONAIRE, SINT EUSTATIUS I SABA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BONAIRE, SINT EUSTATIUS I SABA")]
        BQ,
        
        /// <summary>
        /// <para>BOŚNIA I HERCEGOWINA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BOŚNIA I HERCEGOWINA")]
        BA,
        
        /// <summary>
        /// <para>BOTSWANA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BOTSWANA")]
        BW,
        
        /// <summary>
        /// <para>BRAZYLIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BRAZYLIA")]
        BR,
        
        /// <summary>
        /// <para>BRUNEI DARUSSALAM</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BRUNEI DARUSSALAM")]
        BN,
        
        /// <summary>
        /// <para>BRYTYJSKIE TERYTORIUM OCEANU INDYJSKIEGO</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BRYTYJSKIE TERYTORIUM OCEANU INDYJSKIEGO")]
        IO,
        
        /// <summary>
        /// <para>BUŁGARIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BUŁGARIA")]
        BG,
        
        /// <summary>
        /// <para>BURKINA FASO</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BURKINA FASO")]
        BF,
        
        /// <summary>
        /// <para>BURUNDI</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("BURUNDI")]
        BI,
        
        /// <summary>
        /// <para>CEUTA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("CEUTA")]
        XC,
        
        /// <summary>
        /// <para>CHILE</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("CHILE")]
        CL,
        
        /// <summary>
        /// <para>CHINY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("CHINY")]
        CN,
        
        /// <summary>
        /// <para>CHORWACJA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("CHORWACJA")]
        HR,
        
        /// <summary>
        /// <para>CURAÇAO</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("CURAÇAO")]
        CW,
        
        /// <summary>
        /// <para>CYPR</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("CYPR")]
        CY,
        
        /// <summary>
        /// <para>CZAD</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("CZAD")]
        TD,
        
        /// <summary>
        /// <para>CZARNOGÓRA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("CZARNOGÓRA")]
        ME,
        
        /// <summary>
        /// <para>DANIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("DANIA")]
        DK,
        
        /// <summary>
        /// <para>DOMINIKA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("DOMINIKA")]
        DM,
        
        /// <summary>
        /// <para>DOMINIKANA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("DOMINIKANA")]
        DO,
        
        /// <summary>
        /// <para>DŻIBUTI</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("DŻIBUTI")]
        DJ,
        
        /// <summary>
        /// <para>EGIPT</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("EGIPT")]
        EG,
        
        /// <summary>
        /// <para>EKWADOR</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("EKWADOR")]
        EC,
        
        /// <summary>
        /// <para>ERYTREA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ERYTREA")]
        ER,
        
        /// <summary>
        /// <para>ESTONIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ESTONIA")]
        EE,
        
        /// <summary>
        /// <para>ETIOPIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ETIOPIA")]
        ET,
        
        /// <summary>
        /// <para>FALKLANDY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("FALKLANDY")]
        FK,
        
        /// <summary>
        /// <para>FIDŻI REPUBLIKA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("FIDŻI REPUBLIKA")]
        FJ,
        
        /// <summary>
        /// <para>FILIPINY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("FILIPINY")]
        PH,
        
        /// <summary>
        /// <para>FINLANDIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("FINLANDIA")]
        FI,
        
        /// <summary>
        /// <para>FRANCJA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("FRANCJA")]
        FR,
        
        /// <summary>
        /// <para>FRANCUSKIE TERYTORIUM POŁUDNIOWE</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("FRANCUSKIE TERYTORIUM POŁUDNIOWE")]
        TF,
        
        /// <summary>
        /// <para>GABON</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GABON")]
        GA,
        
        /// <summary>
        /// <para>GAMBIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GAMBIA")]
        GM,
        
        /// <summary>
        /// <para>GHANA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GHANA")]
        GH,
        
        /// <summary>
        /// <para>GIBRALTAR</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GIBRALTAR")]
        GI,
        
        /// <summary>
        /// <para>GRECJA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GRECJA")]
        GR,
        
        /// <summary>
        /// <para>GRENADA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GRENADA")]
        GD,
        
        /// <summary>
        /// <para>GRENLANDIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GRENLANDIA")]
        GL,
        
        /// <summary>
        /// <para>GRUZJA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GRUZJA")]
        GE,
        
        /// <summary>
        /// <para>GUAM</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GUAM")]
        GU,
        
        /// <summary>
        /// <para>GUERNSEY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GUERNSEY")]
        GG,
        
        /// <summary>
        /// <para>GUJANA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GUJANA")]
        GY,
        
        /// <summary>
        /// <para>GUJANA FRANCUSKA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GUJANA FRANCUSKA")]
        GF,
        
        /// <summary>
        /// <para>GWADELUPA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GWADELUPA")]
        GP,
        
        /// <summary>
        /// <para>GWATEMALA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GWATEMALA")]
        GT,
        
        /// <summary>
        /// <para>GWINEA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GWINEA")]
        GN,
        
        /// <summary>
        /// <para>GWINEA RÓWNIKOWA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GWINEA RÓWNIKOWA")]
        GQ,
        
        /// <summary>
        /// <para>GWINEA-BISSAU</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GWINEA-BISSAU")]
        GW,
        
        /// <summary>
        /// <para>HAITI</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("HAITI")]
        HT,
        
        /// <summary>
        /// <para>HISZPANIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("HISZPANIA")]
        ES,
        
        /// <summary>
        /// <para>HONDURAS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("HONDURAS")]
        HN,
        
        /// <summary>
        /// <para>HONGKONG</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("HONGKONG")]
        HK,
        
        /// <summary>
        /// <para>INDIE</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("INDIE")]
        IN,
        
        /// <summary>
        /// <para>INDONEZJA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("INDONEZJA")]
        ID,
        
        /// <summary>
        /// <para>IRAK</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("IRAK")]
        IQ,
        
        /// <summary>
        /// <para>IRAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("IRAN")]
        IR,
        
        /// <summary>
        /// <para>IRLANDIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("IRLANDIA")]
        IE,
        
        /// <summary>
        /// <para>ISLANDIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ISLANDIA")]
        IS,
        
        /// <summary>
        /// <para>IZRAEL</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("IZRAEL")]
        IL,
        
        /// <summary>
        /// <para>JAMAJKA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("JAMAJKA")]
        JM,
        
        /// <summary>
        /// <para>JAPONIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("JAPONIA")]
        JP,
        
        /// <summary>
        /// <para>JEMEN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("JEMEN")]
        YE,
        
        /// <summary>
        /// <para>JERSEY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("JERSEY")]
        JE,
        
        /// <summary>
        /// <para>JORDANIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("JORDANIA")]
        JO,
        
        /// <summary>
        /// <para>KAJMANY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KAJMANY")]
        KY,
        
        /// <summary>
        /// <para>KAMBODŻA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KAMBODŻA")]
        KH,
        
        /// <summary>
        /// <para>KAMERUN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KAMERUN")]
        CM,
        
        /// <summary>
        /// <para>KANADA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KANADA")]
        CA,
        
        /// <summary>
        /// <para>KATAR</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KATAR")]
        QA,
        
        /// <summary>
        /// <para>KAZACHSTAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KAZACHSTAN")]
        KZ,
        
        /// <summary>
        /// <para>KENIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KENIA")]
        KE,
        
        /// <summary>
        /// <para>KIRGISTAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KIRGISTAN")]
        KG,
        
        /// <summary>
        /// <para>KIRIBATI</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KIRIBATI")]
        KI,
        
        /// <summary>
        /// <para>KOLUMBIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KOLUMBIA")]
        CO,
        
        /// <summary>
        /// <para>KOMORY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KOMORY")]
        KM,
        
        /// <summary>
        /// <para>KONGO</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KONGO")]
        CG,
        
        /// <summary>
        /// <para>KONGO, REPUBLIKA DEMOKRATYCZNA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KONGO, REPUBLIKA DEMOKRATYCZNA")]
        CD,
        
        /// <summary>
        /// <para>KOREAŃSKA REPUBLIKA LUDOWO-DEMOKRATYCZNA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KOREAŃSKA REPUBLIKA LUDOWO-DEMOKRATYCZNA")]
        KP,
        
        /// <summary>
        /// <para>KOSOWO</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KOSOWO")]
        XK,
        
        /// <summary>
        /// <para>KOSTARYKA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KOSTARYKA")]
        CR,
        
        /// <summary>
        /// <para>KUBA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KUBA")]
        CU,
        
        /// <summary>
        /// <para>KUWEJT</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("KUWEJT")]
        KW,
        
        /// <summary>
        /// <para>LAOS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("LAOS")]
        LA,
        
        /// <summary>
        /// <para>LESOTHO</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("LESOTHO")]
        LS,
        
        /// <summary>
        /// <para>LIBAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("LIBAN")]
        LB,
        
        /// <summary>
        /// <para>LIBERIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("LIBERIA")]
        LR,
        
        /// <summary>
        /// <para>LIBIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("LIBIA")]
        LY,
        
        /// <summary>
        /// <para>LIECHTENSTEIN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("LIECHTENSTEIN")]
        LI,
        
        /// <summary>
        /// <para>LITWA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("LITWA")]
        LT,
        
        /// <summary>
        /// <para>ŁOTWA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ŁOTWA")]
        LV,
        
        /// <summary>
        /// <para>LUKSEMBURG</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("LUKSEMBURG")]
        LU,
        
        /// <summary>
        /// <para>MACEDONIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MACEDONIA")]
        MK,
        
        /// <summary>
        /// <para>MADAGASKAR</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MADAGASKAR")]
        MG,
        
        /// <summary>
        /// <para>MAJOTTA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MAJOTTA")]
        YT,
        
        /// <summary>
        /// <para>MAKAU</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MAKAU")]
        MO,
        
        /// <summary>
        /// <para>MALAWI</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MALAWI")]
        MW,
        
        /// <summary>
        /// <para>MALEDIWY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MALEDIWY")]
        MV,
        
        /// <summary>
        /// <para>MALEZJA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MALEZJA")]
        MY,
        
        /// <summary>
        /// <para>MALI</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MALI")]
        ML,
        
        /// <summary>
        /// <para>MALTA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MALTA")]
        MT,
        
        /// <summary>
        /// <para>MARIANY PÓŁNOCNE</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MARIANY PÓŁNOCNE")]
        MP,
        
        /// <summary>
        /// <para>MAROKO</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MAROKO")]
        MA,
        
        /// <summary>
        /// <para>MARTYNIKA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MARTYNIKA")]
        MQ,
        
        /// <summary>
        /// <para>MAURETANIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MAURETANIA")]
        MR,
        
        /// <summary>
        /// <para>MAURITIUS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MAURITIUS")]
        MU,
        
        /// <summary>
        /// <para>MEKSYK</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MEKSYK")]
        MX,
        
        /// <summary>
        /// <para>MELILLA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MELILLA")]
        XL,
        
        /// <summary>
        /// <para>MIKRONEZJA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MIKRONEZJA")]
        FM,
        
        /// <summary>
        /// <para>MINOR</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MINOR")]
        UM,
        
        /// <summary>
        /// <para>MOŁDOWA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MOŁDOWA")]
        MD,
        
        /// <summary>
        /// <para>MONAKO</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MONAKO")]
        MC,
        
        /// <summary>
        /// <para>MONGOLIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MONGOLIA")]
        MN,
        
        /// <summary>
        /// <para>MONTSERRAT</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MONTSERRAT")]
        MS,
        
        /// <summary>
        /// <para>MOZAMBIK</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MOZAMBIK")]
        MZ,
        
        /// <summary>
        /// <para>MYANMAR (BURMA)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("MYANMAR (BURMA)")]
        MM,
        
        /// <summary>
        /// <para>NAMIBIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("NAMIBIA")]
        NA,
        
        /// <summary>
        /// <para>NAURU</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("NAURU")]
        NR,
        
        /// <summary>
        /// <para>NEPAL</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("NEPAL")]
        NP,
        
        /// <summary>
        /// <para>NIDERLANDY (HOLANDIA)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("NIDERLANDY (HOLANDIA)")]
        NL,
        
        /// <summary>
        /// <para>NIEMCY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("NIEMCY")]
        DE,
        
        /// <summary>
        /// <para>NIGER</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("NIGER")]
        NE,
        
        /// <summary>
        /// <para>NIGERIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("NIGERIA")]
        NG,
        
        /// <summary>
        /// <para>NIKARAGUA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("NIKARAGUA")]
        NI,
        
        /// <summary>
        /// <para>NIUE</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("NIUE")]
        NU,
        
        /// <summary>
        /// <para>NORFOLK</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("NORFOLK")]
        NF,
        
        /// <summary>
        /// <para>NORWEGIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("NORWEGIA")]
        NO,
        
        /// <summary>
        /// <para>NOWA KALEDONIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("NOWA KALEDONIA")]
        NC,
        
        /// <summary>
        /// <para>NOWA ZELANDIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("NOWA ZELANDIA")]
        NZ,
        
        /// <summary>
        /// <para>OKUPOWANE TERYTORIUM PALESTYNY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("OKUPOWANE TERYTORIUM PALESTYNY")]
        PS,
        
        /// <summary>
        /// <para>OMAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("OMAN")]
        OM,
        
        /// <summary>
        /// <para>PAKISTAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("PAKISTAN")]
        PK,
        
        /// <summary>
        /// <para>PALAU</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("PALAU")]
        PW,
        
        /// <summary>
        /// <para>PANAMA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("PANAMA")]
        PA,
        
        /// <summary>
        /// <para>PAPUA NOWA GWINEA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("PAPUA NOWA GWINEA")]
        PG,
        
        /// <summary>
        /// <para>PARAGWAJ</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("PARAGWAJ")]
        PY,
        
        /// <summary>
        /// <para>PERU</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("PERU")]
        PE,
        
        /// <summary>
        /// <para>PITCAIRN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("PITCAIRN")]
        PN,
        
        /// <summary>
        /// <para>POLINEZJA FRANCUSKA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("POLINEZJA FRANCUSKA")]
        PF,
        
        /// <summary>
        /// <para>POLSKA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("POLSKA")]
        PL,
        
        /// <summary>
        /// <para>POŁUDNIOWA GEORGIA I POŁUD.WYSPY SANDWICH</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("POŁUDNIOWA GEORGIA I POŁUD.WYSPY SANDWICH")]
        GS,
        
        /// <summary>
        /// <para>PORTUGALIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("PORTUGALIA")]
        PT,
        
        /// <summary>
        /// <para>PORTORYKO</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("PORTORYKO")]
        PR,
        
        /// <summary>
        /// <para>REP.ŚRODKOWOAFRYKAŃSKA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("REP.ŚRODKOWOAFRYKAŃSKA")]
        CF,
        
        /// <summary>
        /// <para>REPUBLIKA CZESKA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("REPUBLIKA CZESKA")]
        CZ,
        
        /// <summary>
        /// <para>REPUBLIKA KOREI</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("REPUBLIKA KOREI")]
        KR,
        
        /// <summary>
        /// <para>REPUBLIKA POŁUDNIOWEJ AFRYKI</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("REPUBLIKA POŁUDNIOWEJ AFRYKI")]
        ZA,
        
        /// <summary>
        /// <para>REUNION</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("REUNION")]
        RE,
        
        /// <summary>
        /// <para>ROSJA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ROSJA")]
        RU,
        
        /// <summary>
        /// <para>RUMUNIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("RUMUNIA")]
        RO,
        
        /// <summary>
        /// <para>RWANDA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("RWANDA")]
        RW,
        
        /// <summary>
        /// <para>SAHARA ZACHODNIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SAHARA ZACHODNIA")]
        EH,
        
        /// <summary>
        /// <para>SAINT BARTHELEMY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SAINT BARTHELEMY")]
        BL,
        
        /// <summary>
        /// <para>SAINT KITTS I NEVIS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SAINT KITTS I NEVIS")]
        KN,
        
        /// <summary>
        /// <para>SAINT LUCIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SAINT LUCIA")]
        LC,
        
        /// <summary>
        /// <para>SAINT MARTIN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SAINT MARTIN")]
        MF,
        
        /// <summary>
        /// <para>SAINT VINCENT I GRENADYNY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SAINT VINCENT I GRENADYNY")]
        VC,
        
        /// <summary>
        /// <para>SALWADOR</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SALWADOR")]
        SV,
        
        /// <summary>
        /// <para>SAMOA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SAMOA")]
        WS,
        
        /// <summary>
        /// <para>SAMOA AMERYKAŃSKIE</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SAMOA AMERYKAŃSKIE")]
        AS,
        
        /// <summary>
        /// <para>SAN MARINO</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SAN MARINO")]
        SM,
        
        /// <summary>
        /// <para>SENEGAL</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SENEGAL")]
        SN,
        
        /// <summary>
        /// <para>SERBIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SERBIA")]
        RS,
        
        /// <summary>
        /// <para>SESZELE</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SESZELE")]
        SC,
        
        /// <summary>
        /// <para>SIERRA LEONE</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SIERRA LEONE")]
        SL,
        
        /// <summary>
        /// <para>SINGAPUR</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SINGAPUR")]
        SG,
        
        /// <summary>
        /// <para>SŁOWACJA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SŁOWACJA")]
        SK,
        
        /// <summary>
        /// <para>SŁOWENIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SŁOWENIA")]
        SI,
        
        /// <summary>
        /// <para>SOMALIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SOMALIA")]
        SO,
        
        /// <summary>
        /// <para>SRI LANKA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SRI LANKA")]
        LK,
        
        /// <summary>
        /// <para>SAINT PIERRE I MIQUELON</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SAINT PIERRE I MIQUELON")]
        PM,
        
        /// <summary>
        /// <para>STANY ZJEDNOCZONE AMERYKI</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("STANY ZJEDNOCZONE AMERYKI")]
        US,
        
        /// <summary>
        /// <para>SUAZI</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SUAZI")]
        SZ,
        
        /// <summary>
        /// <para>SUDAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SUDAN")]
        SD,
        
        /// <summary>
        /// <para>SUDAN POŁUDNIOWY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SUDAN POŁUDNIOWY")]
        SS,
        
        /// <summary>
        /// <para>SURINAM</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SURINAM")]
        SR,
        
        /// <summary>
        /// <para>SVALBARD I JAN MAYEN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SVALBARD I JAN MAYEN")]
        SJ,
        
        /// <summary>
        /// <para>ŚWIĘTA HELENA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ŚWIĘTA HELENA")]
        SH,
        
        /// <summary>
        /// <para>SYRIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SYRIA")]
        SY,
        
        /// <summary>
        /// <para>SZWAJCARIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SZWAJCARIA")]
        CH,
        
        /// <summary>
        /// <para>SZWECJA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("SZWECJA")]
        SE,
        
        /// <summary>
        /// <para>TADŻYKISTAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TADŻYKISTAN")]
        TJ,
        
        /// <summary>
        /// <para>TAJLANDIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TAJLANDIA")]
        TH,
        
        /// <summary>
        /// <para>TAJWAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TAJWAN")]
        TW,
        
        /// <summary>
        /// <para>TANZANIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TANZANIA")]
        TZ,
        
        /// <summary>
        /// <para>TOGO</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TOGO")]
        TG,
        
        /// <summary>
        /// <para>TOKELAU</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TOKELAU")]
        TK,
        
        /// <summary>
        /// <para>TONGA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TONGA")]
        TO,
        
        /// <summary>
        /// <para>TRYNIDAD I TOBAGO</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TRYNIDAD I TOBAGO")]
        TT,
        
        /// <summary>
        /// <para>TUNEZJA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TUNEZJA")]
        TN,
        
        /// <summary>
        /// <para>TURCJA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TURCJA")]
        TR,
        
        /// <summary>
        /// <para>TURKMENISTAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TURKMENISTAN")]
        TM,
        
        /// <summary>
        /// <para>TUVALU</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("TUVALU")]
        TV,
        
        /// <summary>
        /// <para>UGANDA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("UGANDA")]
        UG,
        
        /// <summary>
        /// <para>UKRAINA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("UKRAINA")]
        UA,
        
        /// <summary>
        /// <para>URUGWAJ</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("URUGWAJ")]
        UY,
        
        /// <summary>
        /// <para>UZBEKISTAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("UZBEKISTAN")]
        UZ,
        
        /// <summary>
        /// <para>VANUATU</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("VANUATU")]
        VU,
        
        /// <summary>
        /// <para>WALLIS I FUTUNA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WALLIS I FUTUNA")]
        WF,
        
        /// <summary>
        /// <para>WATYKAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WATYKAN")]
        VA,
        
        /// <summary>
        /// <para>WĘGRY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WĘGRY")]
        HU,
        
        /// <summary>
        /// <para>WENEZUELA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WENEZUELA")]
        VE,
        
        /// <summary>
        /// <para>WIELKA BRYTANIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WIELKA BRYTANIA")]
        GB,
        
        /// <summary>
        /// <para>WIETNAM</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WIETNAM")]
        VN,
        
        /// <summary>
        /// <para>WŁOCHY</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WŁOCHY")]
        IT,
        
        /// <summary>
        /// <para>WSCHODNI TIMOR</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WSCHODNI TIMOR")]
        TL,
        
        /// <summary>
        /// <para>WYBRZEŻE KOŚCI SŁONIOWEJ</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WYBRZEŻE KOŚCI SŁONIOWEJ")]
        CI,
        
        /// <summary>
        /// <para>WYSPA BOUVETA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WYSPA BOUVETA")]
        BV,
        
        /// <summary>
        /// <para>WYSPA BOŻEGO NARODZENIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WYSPA BOŻEGO NARODZENIA")]
        CX,
        
        /// <summary>
        /// <para>WYSPA MAN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WYSPA MAN")]
        IM,
        
        /// <summary>
        /// <para>WYSPA SINT MAARTEN (CZĘŚĆ HOLENDERSKA WYSPY)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WYSPA SINT MAARTEN (CZĘŚĆ HOLENDERSKA WYSPY)")]
        SX,
        
        /// <summary>
        /// <para>WYSPY COOKA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WYSPY COOKA")]
        CK,
        
        /// <summary>
        /// <para>WYSPY DZIEWICZE-USA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WYSPY DZIEWICZE-USA")]
        VI,
        
        /// <summary>
        /// <para>WYSPY DZIEWICZE-W.B.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WYSPY DZIEWICZE-W.B.")]
        VG,
        
        /// <summary>
        /// <para>WYSPY HEARD I MCDONALD</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WYSPY HEARD I MCDONALD")]
        HM,
        
        /// <summary>
        /// <para>WYSPY KOKOSOWE (KEELINGA)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WYSPY KOKOSOWE (KEELINGA)")]
        CC,
        
        /// <summary>
        /// <para>WYSPY MARSHALLA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WYSPY MARSHALLA")]
        MH,
        
        /// <summary>
        /// <para>WYSPY OWCZE</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WYSPY OWCZE")]
        FO,
        
        /// <summary>
        /// <para>WYSPY SALOMONA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WYSPY SALOMONA")]
        SB,
        
        /// <summary>
        /// <para>WYSPY ŚWIĘTEGO TOMASZA I KSIĄŻĘCA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WYSPY ŚWIĘTEGO TOMASZA I KSIĄŻĘCA")]
        ST,
        
        /// <summary>
        /// <para>WYSPY TURKS I CAICOS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("WYSPY TURKS I CAICOS")]
        TC,
        
        /// <summary>
        /// <para>ZAMBIA</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ZAMBIA")]
        ZM,
        
        /// <summary>
        /// <para>ZIELONY PRZYLĄDEK</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ZIELONY PRZYLĄDEK")]
        CV,
        
        /// <summary>
        /// <para>ZIMBABWE</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ZIMBABWE")]
        ZW,
        
        /// <summary>
        /// <para>ZJEDNOCZONE EMIRATY ARABSKIE</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ZJEDNOCZONE EMIRATY ARABSKIE")]
        AE,
        
        /// <summary>
        /// <para>ZJEDNOCZONE KRÓLESTWO (IRLANDIA PÓŁNOCNA)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ZJEDNOCZONE KRÓLESTWO (IRLANDIA PÓŁNOCNA)")]
        XI,
        
        /// <summary>
        /// <para>ZJEDNOCZONE KRÓLESTWO (WYŁĄCZAJĄC IRLANDIĘ PÓŁNOCNĄ)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ZJEDNOCZONE KRÓLESTWO (WYŁĄCZAJĄC IRLANDIĘ PÓŁNOCNĄ)")]
        XU,
    }
