//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// XmlSchemaClassGenerator.Console --nullable --namespace http://crd.gov.pl/wzor/2025/12/19/14090/=ProFak.IO.JPK_V7M --namespace http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2023/09/06/eD/KodyKrajow/=ProFak.IO.JPK_V7M.KodyKrajow --namespace http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/KodyUrzedowSkarbowych/=ProFak.IO.JPK_V7M.KodyUrzedowSkarbowych --namespace http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/=ProFak.IO.JPK_V7M.DefinicjeTypy --namingScheme=Direct http://crd.gov.pl/wzor/2025/12/19/14090/schemat.xsd
namespace ProFak.IO.JPK_V7M.DefinicjeTypy
{
    
    
    /// <summary>
    /// <para>Podstawowy zestaw danych identyfikacyjnych o osobie fizycznej</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Podstawowy zestaw danych identyfikacyjnych o osobie fizycznej")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TIdentyfikatorOsobyFizycznej", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TIdentyfikatorOsobyFizycznej
    {
        
        /// <summary>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para xml:lang="en">Pattern: [1-9]((\d[1-9])|([1-9]\d))\d{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identyfikator podatkowy NIP")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]((\\d[1-9])|([1-9]\\d))\\d{7}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("NIP")]
        public string NIP { get; set; }
        
        /// <summary>
        /// <para>Pierwsze imię</para>
        /// <para>Pierwsze imię</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Pierwsze imię")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("ImiePierwsze")]
        public string ImiePierwsze { get; set; }
        
        /// <summary>
        /// <para>Nazwisko</para>
        /// <para>Nazwisko</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 81.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nazwisko")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(81)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("Nazwisko")]
        public string Nazwisko { get; set; }
        
        /// <summary>
        /// <para>Data urodzenia</para>
        /// <para>Typ daty</para>
        /// <para xml:lang="en">Minimum inclusive value: 1900-01-01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 2100-12-31.</para>
        /// <para xml:lang="en">Pattern: ((\d{4})-(\d{2})-(\d{2})).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data urodzenia")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((\\d{4})-(\\d{2})-(\\d{2}))")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.DateTime), "1900-01-01", "2100-12-31")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DataUrodzenia", DataType="date")]
        public System.DateTime DataUrodzenia { get; set; }
        
        /// <summary>
        /// <para>Identyfikator podatkowy numer PESEL</para>
        /// <para>Identyfikator podatkowy numer PESEL</para>
        /// <para xml:lang="en">Pattern: \d{11}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identyfikator podatkowy numer PESEL")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{11}")]
        [System.Xml.Serialization.XmlElementAttribute("PESEL")]
        public string PESEL { get; set; }
    }
    
    /// <summary>
    /// <para>Określa, czy to jest złożenie, czy korekta dokumentu</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Określa, czy to jest złożenie, czy korekta dokumentu")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCelZlozenia", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    public enum TCelZlozenia
    {
        
        /// <summary>
        /// <para>złożenie po raz pierwszy deklaracji za dany okres</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("złożenie po raz pierwszy deklaracji za dany okres")]
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <summary>
        /// <para>korekta deklaracji za dany okres</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("korekta deklaracji za dany okres")]
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <summary>
    /// <para>Pojedyncze pole wyboru</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Pojedyncze pole wyboru")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TWybor1", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    public enum TWybor1
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <summary>
    /// <para>Podwójne pole wyboru</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Podwójne pole wyboru")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TWybor1_2", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    public enum TWybor1_2
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <summary>
    /// <para>Potrójne pole wyboru</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Potrójne pole wyboru")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TWybor1_3", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    public enum TWybor1_3
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <summary>
    /// <para>Podstawowy zestaw danych identyfikacyjnych o osobie fizycznej z identyfikatorem NIP albo PESEL</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Podstawowy zestaw danych identyfikacyjnych o osobie fizycznej z identyfikatorem N" +
        "IP albo PESEL")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TIdentyfikatorOsobyFizycznej1", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TIdentyfikatorOsobyFizycznej1
    {
        
        /// <summary>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para xml:lang="en">Pattern: [1-9]((\d[1-9])|([1-9]\d))\d{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identyfikator podatkowy NIP")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]((\\d[1-9])|([1-9]\\d))\\d{7}")]
        [System.Xml.Serialization.XmlElementAttribute("NIP")]
        public string NIP { get; set; }
        
        /// <summary>
        /// <para>Identyfikator podatkowy numer PESEL</para>
        /// <para>Identyfikator podatkowy numer PESEL</para>
        /// <para xml:lang="en">Pattern: \d{11}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identyfikator podatkowy numer PESEL")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{11}")]
        [System.Xml.Serialization.XmlElementAttribute("PESEL")]
        public string PESEL { get; set; }
        
        /// <summary>
        /// <para>Pierwsze imię</para>
        /// <para>Pierwsze imię</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Pierwsze imię")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("ImiePierwsze")]
        public string ImiePierwsze { get; set; }
        
        /// <summary>
        /// <para>Nazwisko</para>
        /// <para>Nazwisko</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 81.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nazwisko")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(81)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("Nazwisko")]
        public string Nazwisko { get; set; }
        
        /// <summary>
        /// <para>Data urodzenia</para>
        /// <para>Typ daty</para>
        /// <para xml:lang="en">Minimum inclusive value: 1900-01-01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 2100-12-31.</para>
        /// <para xml:lang="en">Pattern: ((\d{4})-(\d{2})-(\d{2})).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data urodzenia")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((\\d{4})-(\\d{2})-(\\d{2}))")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.DateTime), "1900-01-01", "2100-12-31")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DataUrodzenia", DataType="date")]
        public System.DateTime DataUrodzenia { get; set; }
    }
    
    /// <summary>
    /// <para>Podstawowy zestaw danych identyfikacyjnych o osobie fizycznej z identyfikatorem NIP</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Podstawowy zestaw danych identyfikacyjnych o osobie fizycznej z identyfikatorem N" +
        "IP")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TIdentyfikatorOsobyFizycznej2", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProFak.IO.JPK_V7M.TPodmiotDowolnyBezAdresuOsobaFizyczna))]
    public partial class TIdentyfikatorOsobyFizycznej2
    {
        
        /// <summary>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para xml:lang="en">Pattern: [1-9]((\d[1-9])|([1-9]\d))\d{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identyfikator podatkowy NIP")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]((\\d[1-9])|([1-9]\\d))\\d{7}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("NIP")]
        public string NIP { get; set; }
        
        /// <summary>
        /// <para>Pierwsze imię</para>
        /// <para>Pierwsze imię</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Pierwsze imię")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("ImiePierwsze")]
        public string ImiePierwsze { get; set; }
        
        /// <summary>
        /// <para>Nazwisko</para>
        /// <para>Nazwisko</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 81.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nazwisko")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(81)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("Nazwisko")]
        public string Nazwisko { get; set; }
        
        /// <summary>
        /// <para>Data urodzenia</para>
        /// <para>Typ daty</para>
        /// <para xml:lang="en">Minimum inclusive value: 1900-01-01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 2100-12-31.</para>
        /// <para xml:lang="en">Pattern: ((\d{4})-(\d{2})-(\d{2})).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data urodzenia")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((\\d{4})-(\\d{2})-(\\d{2}))")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.DateTime), "1900-01-01", "2100-12-31")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DataUrodzenia", DataType="date")]
        public System.DateTime DataUrodzenia { get; set; }
    }
    
    /// <summary>
    /// <para>Pełny zestaw danych identyfikacyjnych o osobie fizycznej</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Pełny zestaw danych identyfikacyjnych o osobie fizycznej")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TIdentyfikatorOsobyFizycznejPelny", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TIdentyfikatorOsobyFizycznejPelny
    {
        
        /// <summary>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para xml:lang="en">Pattern: [1-9]((\d[1-9])|([1-9]\d))\d{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identyfikator podatkowy NIP")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]((\\d[1-9])|([1-9]\\d))\\d{7}")]
        [System.Xml.Serialization.XmlElementAttribute("NIP")]
        public string NIP { get; set; }
        
        /// <summary>
        /// <para>Pierwsze imię</para>
        /// <para>Pierwsze imię</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Pierwsze imię")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("ImiePierwsze")]
        public string ImiePierwsze { get; set; }
        
        /// <summary>
        /// <para>Nazwisko</para>
        /// <para>Nazwisko</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 81.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nazwisko")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(81)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("Nazwisko")]
        public string Nazwisko { get; set; }
        
        /// <summary>
        /// <para>Data urodzenia</para>
        /// <para>Typ daty</para>
        /// <para xml:lang="en">Minimum inclusive value: 1900-01-01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 2100-12-31.</para>
        /// <para xml:lang="en">Pattern: ((\d{4})-(\d{2})-(\d{2})).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data urodzenia")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((\\d{4})-(\\d{2})-(\\d{2}))")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.DateTime), "1900-01-01", "2100-12-31")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DataUrodzenia", DataType="date")]
        public System.DateTime DataUrodzenia { get; set; }
        
        /// <summary>
        /// <para>Imię ojca</para>
        /// <para>Pierwsze imię</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Imię ojca")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("ImieOjca")]
        public string ImieOjca { get; set; }
        
        /// <summary>
        /// <para>Imię matki</para>
        /// <para>Pierwsze imię</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Imię matki")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("ImieMatki")]
        public string ImieMatki { get; set; }
        
        /// <summary>
        /// <para>Identyfikator podatkowy numer PESEL</para>
        /// <para>Identyfikator podatkowy numer PESEL</para>
        /// <para xml:lang="en">Pattern: \d{11}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identyfikator podatkowy numer PESEL")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{11}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PESEL")]
        public string PESEL { get; set; }
    }
    
    /// <summary>
    /// <para>Zestaw danych identyfikacyjnych dla osoby fizycznej zagranicznej</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Zestaw danych identyfikacyjnych dla osoby fizycznej zagranicznej")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TIdentyfikatorOsobyFizycznejZagranicznej", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TIdentyfikatorOsobyFizycznejZagranicznej
    {
        
        /// <summary>
        /// <para>Imię pierwsze [First name]</para>
        /// <para>Pierwsze imię</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Imię pierwsze [First name]")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("ImiePierwsze")]
        public string ImiePierwsze { get; set; }
        
        /// <summary>
        /// <para>Nazwisko [Family name]</para>
        /// <para>Nazwisko</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 81.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nazwisko [Family name]")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(81)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("Nazwisko")]
        public string Nazwisko { get; set; }
        
        /// <summary>
        /// <para>Data urodzenia [Date of Birth]</para>
        /// <para>Typ daty</para>
        /// <para xml:lang="en">Minimum inclusive value: 1900-01-01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 2100-12-31.</para>
        /// <para xml:lang="en">Pattern: ((\d{4})-(\d{2})-(\d{2})).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data urodzenia [Date of Birth]")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((\\d{4})-(\\d{2})-(\\d{2}))")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.DateTime), "1900-01-01", "2100-12-31")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DataUrodzenia", DataType="date")]
        public System.DateTime DataUrodzenia { get; set; }
        
        /// <summary>
        /// <para>Miejsce urodzenia [Place of Birth]</para>
        /// <para>Typ określający nazwę miejscowości</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 56.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Miejsce urodzenia [Place of Birth]")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(56)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("MiejsceUrodzenia")]
        public string MiejsceUrodzenia { get; set; }
        
        /// <summary>
        /// <para>Imię ojca [Father’s name]</para>
        /// <para>Pierwsze imię</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Imię ojca [Father’s name]")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.Xml.Serialization.XmlElementAttribute("ImieOjca")]
        public string ImieOjca { get; set; }
        
        /// <summary>
        /// <para>Imię matki [Mother’s name]</para>
        /// <para>Pierwsze imię</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Imię matki [Mother’s name]")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.Xml.Serialization.XmlElementAttribute("ImieMatki")]
        public string ImieMatki { get; set; }
        
        /// <summary>
        /// <para>Identyfikator podatkowy NIP [Tax Identification Number (NIP)]</para>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para xml:lang="en">Pattern: [1-9]((\d[1-9])|([1-9]\d))\d{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identyfikator podatkowy NIP [Tax Identification Number (NIP)]")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]((\\d[1-9])|([1-9]\\d))\\d{7}")]
        [System.Xml.Serialization.XmlElementAttribute("NIP")]
        public string NIP { get; set; }
    }
    
    /// <summary>
    /// <para>Podstawowy zestaw danych identyfikacyjnych o osobie niefizycznej</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Podstawowy zestaw danych identyfikacyjnych o osobie niefizycznej")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TIdentyfikatorOsobyNiefizycznej", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("TIdentyfikatorOsobyNiefizycznej", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    public partial class TIdentyfikatorOsobyNiefizycznej
    {
        
        /// <summary>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para xml:lang="en">Pattern: [1-9]((\d[1-9])|([1-9]\d))\d{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identyfikator podatkowy NIP")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]((\\d[1-9])|([1-9]\\d))\\d{7}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("NIP")]
        public string NIP { get; set; }
        
        /// <summary>
        /// <para>Pełna nazwa</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 240.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Pełna nazwa")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(240)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("PelnaNazwa")]
        public string PelnaNazwa { get; set; }
        
        /// <summary>
        /// <para>Numer REGON</para>
        /// <para>Numer REGON</para>
        /// <para xml:lang="en">Pattern: (\d{9})|(\d{14}).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Numer REGON")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(\\d{9})|(\\d{14})")]
        [System.Xml.Serialization.XmlElementAttribute("REGON")]
        public string REGON { get; set; }
    }
    
    /// <summary>
    /// <para>Podstawowy zestaw danych identyfikacyjnych o osobie niefizycznej  - bez elementu Numer REGON</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Podstawowy zestaw danych identyfikacyjnych o osobie niefizycznej - bez elementu N" +
        "umer REGON")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TIdentyfikatorOsobyNiefizycznej1", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TIdentyfikatorOsobyNiefizycznej1
    {
        
        /// <summary>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para xml:lang="en">Pattern: [1-9]((\d[1-9])|([1-9]\d))\d{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identyfikator podatkowy NIP")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]((\\d[1-9])|([1-9]\\d))\\d{7}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("NIP")]
        public string NIP { get; set; }
        
        /// <summary>
        /// <para>Pełna nazwa</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 240.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Pełna nazwa")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(240)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("PelnaNazwa")]
        public string PelnaNazwa { get; set; }
    }
    
    /// <summary>
    /// <para>Pełny zestaw danych identyfikacyjnych o osobie niefizycznej</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Pełny zestaw danych identyfikacyjnych o osobie niefizycznej")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TIdentyfikatorOsobyNiefizycznejPelny", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TIdentyfikatorOsobyNiefizycznejPelny
    {
        
        /// <summary>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para xml:lang="en">Pattern: [1-9]((\d[1-9])|([1-9]\d))\d{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identyfikator podatkowy NIP")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]((\\d[1-9])|([1-9]\\d))\\d{7}")]
        [System.Xml.Serialization.XmlElementAttribute("NIP")]
        public string NIP { get; set; }
        
        /// <summary>
        /// <para>Pełna nazwa</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 240.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Pełna nazwa")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(240)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("PelnaNazwa")]
        public string PelnaNazwa { get; set; }
        
        /// <summary>
        /// <para>Skrócona nazwa</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 70.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Skrócona nazwa")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(70)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("SkroconaNazwa")]
        public string SkroconaNazwa { get; set; }
        
        /// <summary>
        /// <para>Numer REGON</para>
        /// <para>Numer REGON</para>
        /// <para xml:lang="en">Pattern: (\d{9})|(\d{14}).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Numer REGON")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(\\d{9})|(\\d{14})")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("REGON")]
        public string REGON { get; set; }
    }
    
    /// <summary>
    /// <para>Zestaw danych identyfikacyjnych dla osoby niefizycznej zagranicznej</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Zestaw danych identyfikacyjnych dla osoby niefizycznej zagranicznej")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TIdentyfikatorOsobyNiefizycznejZagranicznej", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TIdentyfikatorOsobyNiefizycznejZagranicznej
    {
        
        /// <summary>
        /// <para>Pełna nazwa [Name]</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 240.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Pełna nazwa [Name]")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(240)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("PelnaNazwa")]
        public string PelnaNazwa { get; set; }
        
        /// <summary>
        /// <para>Nazwa skrócona [Short Name]</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 70.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nazwa skrócona [Short Name]")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(70)]
        [System.Xml.Serialization.XmlElementAttribute("SkroconaNazwa")]
        public string SkroconaNazwa { get; set; }
        
        /// <summary>
        /// <para>Identyfikator podatkowy NIP [Tax Identification Number (NIP)]</para>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para xml:lang="en">Pattern: [1-9]((\d[1-9])|([1-9]\d))\d{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identyfikator podatkowy NIP [Tax Identification Number (NIP)]")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]((\\d[1-9])|([1-9]\\d))\\d{7}")]
        [System.Xml.Serialization.XmlElementAttribute("NIP")]
        public string NIP { get; set; }
    }
    
    /// <summary>
    /// <para>Skrócony zestaw danych o osobie fizycznej lub niefizycznej</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Skrócony zestaw danych o osobie fizycznej lub niefizycznej")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TPodmiotDowolnyBezAdresu", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("TPodmiotDowolnyBezAdresu", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    public partial class TPodmiotDowolnyBezAdresu
    {
        
        [System.Xml.Serialization.XmlElementAttribute("OsobaFizyczna")]
        public TIdentyfikatorOsobyFizycznej OsobaFizyczna { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OsobaNiefizyczna")]
        public TIdentyfikatorOsobyNiefizycznej OsobaNiefizyczna { get; set; }
    }
    
    /// <summary>
    /// <para>Skrócony zestaw danych o osobie fizycznej lub niefizycznej z identyfikatorem NIP albo PESEL</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Skrócony zestaw danych o osobie fizycznej lub niefizycznej z identyfikatorem NIP " +
        "albo PESEL")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TPodmiotDowolnyBezAdresu1", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TPodmiotDowolnyBezAdresu1
    {
        
        [System.Xml.Serialization.XmlElementAttribute("OsobaFizyczna")]
        public TIdentyfikatorOsobyFizycznej1 OsobaFizyczna { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OsobaNiefizyczna")]
        public TIdentyfikatorOsobyNiefizycznej OsobaNiefizyczna { get; set; }
    }
    
    /// <summary>
    /// <para>Skrócony zestaw danych o osobie fizycznej lub niefizycznej z identyfikatorem NIP</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Skrócony zestaw danych o osobie fizycznej lub niefizycznej z identyfikatorem NIP")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TPodmiotDowolnyBezAdresu2", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TPodmiotDowolnyBezAdresu2
    {
        
        [System.Xml.Serialization.XmlElementAttribute("OsobaFizyczna")]
        public TIdentyfikatorOsobyFizycznej2 OsobaFizyczna { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OsobaNiefizyczna")]
        public TIdentyfikatorOsobyNiefizycznej OsobaNiefizyczna { get; set; }
    }
    
    /// <summary>
    /// <para>Skrócony zestaw danych o osobie fizycznej lub niefizycznej z identyfikatorem NIP - bez elementu numer REGON dla osoby niefizycznej</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Skrócony zestaw danych o osobie fizycznej lub niefizycznej z identyfikatorem NIP " +
        "- bez elementu numer REGON dla osoby niefizycznej")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TPodmiotDowolnyBezAdresu3", Namespace="http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/09/13/eD/DefinicjeTypy/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TPodmiotDowolnyBezAdresu3
    {
        
        [System.Xml.Serialization.XmlElementAttribute("OsobaFizyczna")]
        public TIdentyfikatorOsobyFizycznej2 OsobaFizyczna { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OsobaNiefizyczna")]
        public TIdentyfikatorOsobyNiefizycznej1 OsobaNiefizyczna { get; set; }
    }
}
