//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// XmlSchemaClassGenerator.Console --nullable --namespace http://jpk.mf.gov.pl/wzor/2024/10/30/10301/=ProFak.IO.JPK_EWP --namespace http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/=ProFak.IO.JPK_EWP.DefinicjeTypy --namespace http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/KodyUrzedowSkarbowych/=ProFak.IO.JPK_EWP.KodyUrzedowSkarbowych --namingScheme=Direct Struktura_Schemat_JPK_EWP(4)_v1-0.xsd
namespace ProFak.IO.JPK_EWP;

    
    
    /// <summary>
    /// <para>Nagłówek JPK_EWP</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Nagłówek JPK_EWP")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNaglowek", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TNaglowek
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("KodFormularza")]
        public TNaglowekKodFormularza KodFormularza { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("WariantFormularza")]
        public TNaglowekWariantFormularza WariantFormularza { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CelZlozenia")]
        public TCelZlozenia CelZlozenia { get; set; }
        
        /// <summary>
        /// <para>Data i czas wytworzenia JPK_EWP</para>
        /// <para>Typ daty i godziny</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data i czas wytworzenia JPK_EWP")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DataWytworzeniaJPK", DataType="dateTime")]
        public System.DateTime DataWytworzeniaJPK { get; set; }
        
        /// <summary>
        /// <para>Data początkowa okresu, którego dotyczy JPK_EWP</para>
        /// <para>Typ daty</para>
        /// <para xml:lang="en">Minimum inclusive value: 1900-01-01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 2050-12-31.</para>
        /// <para xml:lang="en">Pattern: ((\d{4})-(\d{2})-(\d{2})).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data początkowa okresu, którego dotyczy JPK_EWP")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((\\d{4})-(\\d{2})-(\\d{2}))")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.DateTime), "1900-01-01", "2050-12-31")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DataOd", DataType="date")]
        public System.DateTime DataOd { get; set; }
        
        /// <summary>
        /// <para>Data końcowa okresu, którego dotyczy JPK_EWP</para>
        /// <para>Typ daty</para>
        /// <para xml:lang="en">Minimum inclusive value: 1900-01-01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 2050-12-31.</para>
        /// <para xml:lang="en">Pattern: ((\d{4})-(\d{2})-(\d{2})).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data końcowa okresu, którego dotyczy JPK_EWP")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((\\d{4})-(\\d{2})-(\\d{2}))")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.DateTime), "1900-01-01", "2050-12-31")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DataDo", DataType="date")]
        public System.DateTime DataDo { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("KodUrzedu")]
        public ProFak.IO.JPK_EWP.KodyUrzedowSkarbowych.TKodUS KodUrzedu { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNaglowekKodFormularza", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TNaglowekKodFormularza
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public TKodFormularza Value { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _kodSystemowy = "JPK_EWP (4)";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("kodSystemowy")]
        public string kodSystemowy
        {
            get
            {
                return _kodSystemowy;
            }
            set
            {
                _kodSystemowy = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _wersjaSchemy = "1-0";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("wersjaSchemy")]
        public string wersjaSchemy
        {
            get
            {
                return _wersjaSchemy;
            }
            set
            {
                _wersjaSchemy = value;
            }
        }
    }
    
    /// <summary>
    /// <para>Symbol wzoru formularza</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Symbol wzoru formularza")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TKodFormularza", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/")]
    public enum TKodFormularza
    {
        
        JPK_EWP,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TNaglowekWariantFormularza", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/", AnonymousType=true)]
    public enum TNaglowekWariantFormularza
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <summary>
    /// <para>Określenie celu złożenia JPK</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Określenie celu złożenia JPK")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCelZlozenia", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/")]
    [System.Xml.Serialization.XmlRootAttribute("TCelZlozenia", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/")]
    public enum TCelZlozenia
    {
        
        /// <summary>
        /// <para>złożenie JPK na żądanie</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("złożenie JPK na żądanie")]
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <summary>
        /// <para>złożenie JPK po raz pierwszy</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("złożenie JPK po raz pierwszy")]
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <summary>
        /// <para>złożenie korekty JPK</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("złożenie korekty JPK")]
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <summary>
    /// <para>Stawka podatku</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Stawka podatku")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TStawkaPodatku", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/")]
    public enum TStawkaPodatku
    {
        
        /// <summary>
        /// <para>Stawka podatku 17%</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Stawka podatku 17%")]
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        
        /// <summary>
        /// <para>Stawka podatku 15%</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Stawka podatku 15%")]
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        
        /// <summary>
        /// <para>Stawka podatku 14%</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Stawka podatku 14%")]
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        
        /// <summary>
        /// <para>Stawka podatku 12.5%</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Stawka podatku 12.5%")]
        [System.Xml.Serialization.XmlEnumAttribute("12.5")]
        Item12Period5,
        
        /// <summary>
        /// <para>Stawka podatku 12%</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Stawka podatku 12%")]
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <summary>
        /// <para>Stawka podatku 10%</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Stawka podatku 10%")]
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <summary>
        /// <para>Stawka podatku 8.5%</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Stawka podatku 8.5%")]
        [System.Xml.Serialization.XmlEnumAttribute("8.5")]
        Item8Period5,
        
        /// <summary>
        /// <para>Stawka podatku 5.5%</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Stawka podatku 5.5%")]
        [System.Xml.Serialization.XmlEnumAttribute("5.5")]
        Item5Period5,
        
        /// <summary>
        /// <para>Stawka podatku 3%</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Stawka podatku 3%")]
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <summary>
    /// <para>Podstawowy zestaw danych identyfikacyjnych o osobie niefizycznej</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Podstawowy zestaw danych identyfikacyjnych o osobie niefizycznej")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TIdentyfikatorOsobyNiefizycznej", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("TIdentyfikatorOsobyNiefizycznej", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TPodmiotDowolnyBezAdresuOsobaNiefizyczna))]
    public partial class TIdentyfikatorOsobyNiefizycznej
    {
        
        /// <summary>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para>Identyfikator podatkowy NIP</para>
        /// <para xml:lang="en">Pattern: [1-9]((\d[1-9])|([1-9]\d))\d{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identyfikator podatkowy NIP")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]((\\d[1-9])|([1-9]\\d))\\d{7}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("NIP")]
        public string NIP { get; set; }
        
        /// <summary>
        /// <para>Pełna nazwa</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 240.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Pełna nazwa")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(240)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("PelnaNazwa")]
        public string PelnaNazwa { get; set; }
    }
    
    /// <summary>
    /// <para>Skrócony zestaw danych o osobie fizycznej lub niefizycznej z identyfikatorem NIP</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Skrócony zestaw danych o osobie fizycznej lub niefizycznej z identyfikatorem NIP")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TPodmiotDowolnyBezAdresu", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("TPodmiotDowolnyBezAdresu", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JPKPodmiot1))]
    public partial class TPodmiotDowolnyBezAdresu
    {
        
        [System.Xml.Serialization.XmlElementAttribute("OsobaFizyczna")]
        public TPodmiotDowolnyBezAdresuOsobaFizyczna OsobaFizyczna { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OsobaNiefizyczna")]
        public TPodmiotDowolnyBezAdresuOsobaNiefizyczna OsobaNiefizyczna { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TPodmiotDowolnyBezAdresuOsobaFizyczna", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TPodmiotDowolnyBezAdresuOsobaFizyczna : ProFak.IO.JPK_EWP.DefinicjeTypy.TIdentyfikatorOsobyFizycznej2
    {
        
        /// <summary>
        /// <para>Adres poczty elektronicznej</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// <para xml:lang="en">Pattern: (.)+@(.)+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(3)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(.)+@(.)+")]
        [System.Xml.Serialization.XmlElementAttribute("Email")]
        public string Email { get; set; }
        
        /// <summary>
        /// <para>Numer telefonu kontaktowego</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 16.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Numer telefonu kontaktowego")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(16)]
        [System.Xml.Serialization.XmlElementAttribute("Telefon")]
        public string Telefon { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TPodmiotDowolnyBezAdresuOsobaNiefizyczna", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TPodmiotDowolnyBezAdresuOsobaNiefizyczna : TIdentyfikatorOsobyNiefizycznej
    {
        
        /// <summary>
        /// <para>Adres poczty elektronicznej</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// <para xml:lang="en">Pattern: (.)+@(.)+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(3)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(.)+@(.)+")]
        [System.Xml.Serialization.XmlElementAttribute("Email")]
        public string Email { get; set; }
        
        /// <summary>
        /// <para>Numer telefonu kontaktowego</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 16.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Numer telefonu kontaktowego")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(16)]
        [System.Xml.Serialization.XmlElementAttribute("Telefon")]
        public string Telefon { get; set; }
    }
    
    /// <summary>
    /// <para>Jednolity plik kontrolny dla ewidencji przychodów</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Jednolity plik kontrolny dla ewidencji przychodów")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JPK", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("JPK", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/")]
    public partial class JPK
    {
        
        /// <summary>
        /// <para>Nagłówek JPK_EWP</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nagłówek JPK_EWP")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Naglowek")]
        public TNaglowek Naglowek { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Podmiot1")]
        public JPKPodmiot1 Podmiot1 { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<JPKEWPWiersz> _eWPWiersz;
        
        [System.Xml.Serialization.XmlElementAttribute("EWPWiersz")]
        public System.Collections.ObjectModel.Collection<JPKEWPWiersz> EWPWiersz
        {
            get
            {
                return _eWPWiersz;
            }
            private set
            {
                _eWPWiersz = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the EWPWiersz collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EWPWierszSpecified
        {
            get
            {
                return (this.EWPWiersz.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="JPK" /> class.</para>
        /// </summary>
        public JPK()
        {
            this._eWPWiersz = new System.Collections.ObjectModel.Collection<JPKEWPWiersz>();
        }
        
        /// <summary>
        /// <para>Sumy kontrolne dla tabeli EWPWiersz</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Sumy kontrolne dla tabeli EWPWiersz")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("EWPCtrl")]
        public JPKEWPCtrl EWPCtrl { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JPKPodmiot1", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JPKPodmiot1 : TPodmiotDowolnyBezAdresu
    {
        
        /// <summary>
        /// <para>Znacznik dla podatnika rozliczającego podatek metodą kasową</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Znacznik dla podatnika rozliczającego podatek metodą kasową")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Kasowy_PIT")]
        public ProFak.IO.JPK_EWP.DefinicjeTypy.TWybor1 Kasowy_PITValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Kasowy_PIT property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool Kasowy_PITValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Znacznik dla podatnika rozliczającego podatek metodą kasową</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<ProFak.IO.JPK_EWP.DefinicjeTypy.TWybor1> Kasowy_PIT
        {
            get
            {
                if (this.Kasowy_PITValueSpecified)
                {
                    return this.Kasowy_PITValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.Kasowy_PITValue = value.GetValueOrDefault();
                this.Kasowy_PITValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _rola = "Podatnik";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("rola")]
        public string rola
        {
            get
            {
                return _rola;
            }
            set
            {
                _rola = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JPKEWPWiersz", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JPKEWPWiersz
    {
        
        /// <summary>
        /// <para>Lp.</para>
        /// <para>Liczby naturalne większe od zera</para>
        /// <para xml:lang="en">Total number of digits: 14.</para>
        /// <para xml:lang="en">Minimum exclusive value: 0.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Lp.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("K_1")]
        public ulong K_1 { get; set; }
        
        /// <summary>
        /// <para>Data wpisu</para>
        /// <para>Typ daty</para>
        /// <para xml:lang="en">Minimum inclusive value: 1900-01-01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 2050-12-31.</para>
        /// <para xml:lang="en">Pattern: ((\d{4})-(\d{2})-(\d{2})).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data wpisu")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((\\d{4})-(\\d{2})-(\\d{2}))")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.DateTime), "1900-01-01", "2050-12-31")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("K_2", DataType="date")]
        public System.DateTime K_2 { get; set; }
        
        /// <summary>
        /// <para>Data uzyskania przychodu</para>
        /// <para>Typ daty</para>
        /// <para xml:lang="en">Minimum inclusive value: 1900-01-01.</para>
        /// <para xml:lang="en">Maximum inclusive value: 2050-12-31.</para>
        /// <para xml:lang="en">Pattern: ((\d{4})-(\d{2})-(\d{2})).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data uzyskania przychodu")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((\\d{4})-(\\d{2})-(\\d{2}))")]
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(System.DateTime), "1900-01-01", "2050-12-31")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("K_3", DataType="date")]
        public System.DateTime K_3 { get; set; }
        
        /// <summary>
        /// <para>Numer dowodu, na podstawie którego dokonano wpisu</para>
        /// <para>Typ znakowy ograniczony do 256 znaków</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Numer dowodu, na podstawie którego dokonano wpisu")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("K_4")]
        public string K_4 { get; set; }
        
        /// <summary>
        /// <para>Numer identyfikujący fakturę wystawioną przy użyciu Krajowego Systemu e-Faktur (numer KSeF)</para>
        /// <para>Numer identyfikujący fakturę w Krajowym Systemie e-Faktur (KSeF)</para>
        /// <para xml:lang="en">Pattern: ([1-9]((\d[1-9])|([1-9]\d))\d{7}|M\d{9}|[A-Z]{3}\d{7})-(20[2-9][0-9]|2[1-9][0-9]{2}|[3-9][0-9]{3})(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])-([0-9A-F]{6})-?([0-9A-F]{6})-([0-9A-F]{2}).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Numer identyfikujący fakturę wystawioną przy użyciu Krajowego Systemu e-Faktur (n" +
            "umer KSeF)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([1-9]((\\d[1-9])|([1-9]\\d))\\d{7}|M\\d{9}|[A-Z]{3}\\d{7})-(20[2-9][0-9]|2[1-9][0-9]{" +
            "2}|[3-9][0-9]{3})(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])-([0-9A-F]{6})-?([0-9A" +
            "-F]{6})-([0-9A-F]{2})")]
        [System.Xml.Serialization.XmlElementAttribute("K_5")]
        public string K_5 { get; set; }
        
        /// <summary>
        /// <para>Kod kraju nadania identyfikatora podatkowego</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Kod kraju nadania identyfikatora podatkowego")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("K_6")]
        public ProFak.IO.JPK_EWP.DefinicjeTypy.TKodKraju K_6Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the K_6 property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool K_6ValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Kod kraju nadania identyfikatora podatkowego</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<ProFak.IO.JPK_EWP.DefinicjeTypy.TKodKraju> K_6
        {
            get
            {
                if (this.K_6ValueSpecified)
                {
                    return this.K_6Value;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.K_6Value = value.GetValueOrDefault();
                this.K_6ValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para>Numer identyfikacji podatkowej kontrahenta</para>
        /// <para>Numer służący identyfikacji dla celów podatkowych</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Numer identyfikacji podatkowej kontrahenta")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("K_7")]
        public string K_7 { get; set; }
        
        /// <summary>
        /// <para>Kwota przychodu w PLN</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Kwota przychodu w PLN")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("K_8")]
        public decimal K_8 { get; set; }
        
        /// <summary>
        /// <para>Stawka podatku dla kwoty przychodu</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Stawka podatku dla kwoty przychodu")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("K_9")]
        public TStawkaPodatku K_9 { get; set; }
        
        /// <summary>
        /// <para>Uwagi - Podatnicy, którzy zamierzają skorzystać z przewidzianej w art. 21 ust. 1a ustawy możliwości kwartalnego wpłacania ryczałtu od przychodów ewidencjonowanych, w kolumnie „Uwagi” mogą wpisywać datę otrzymania przychodu. Podatnicy, którzy na podstawie art. 15 ust. 1a ustawy są obowiązani w prowadzonej ewidencji wyodrębnić przychody objęte odpowiednio podatkiem tonażowym albo zryczałtowanym podatkiem od wartości sprzedanej produkcji i ryczałtem od przychodów ewidencjonowanych, przychody objęte odpowiednio podatkiem tonażowym albo zryczałtowanym podatkiem od wartości sprzedanej produkcji wykazują wyłącznie w kolumnie „Uwagi”.</para>
        /// <para>Typ znakowy ograniczony do 256 znaków</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Uwagi - Podatnicy, którzy zamierzają skorzystać z przewidzianej w art. 21 ust. 1a ustawy możliwości kwartalnego wpłacania ryczałtu od przychodów ewidencjonowanych, w kolumnie „Uwagi” mogą wpisywać datę otrzymania przychodu. Podatnicy, którzy na podstawie art. 15 ust. 1a ustawy są obowiązani w prowadzonej ewidencji wyodrębnić przychody objęte odpowiednio podatkiem tonażowym albo zryczałtowanym podatkiem od wartości sprzedanej produkcji i ryczałtem od przychodów ewidencjonowanych, przychody objęte odpowiednio podatkiem tonażowym albo zryczałtowanym podatkiem od wartości sprzedanej produkcji wykazują wyłącznie w kolumnie „Uwagi”.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.Xml.Serialization.XmlElementAttribute("K_10")]
        public string K_10 { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JPKEWPCtrl", Namespace="http://jpk.mf.gov.pl/wzor/2024/10/30/10301/", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JPKEWPCtrl
    {
        
        /// <summary>
        /// <para>Liczba wierszy (zapisów) ewidencji przychodów, w okresie którego dotyczy JPK_EWP</para>
        /// <para>Liczby naturalne większe od zera</para>
        /// <para xml:lang="en">Total number of digits: 14.</para>
        /// <para xml:lang="en">Minimum exclusive value: 0.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Liczba wierszy (zapisów) ewidencji przychodów, w okresie którego dotyczy JPK_EWP")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("LiczbaWierszy")]
        public ulong LiczbaWierszy { get; set; }
        
        /// <summary>
        /// <para>Łączna wartość przychodów (K_8) w ewidencji przychodów w okresie, którego dotyczy JPK_EWP</para>
        /// <para>Wartość numeryczna 18 znaków max, w tym 2 znaki po przecinku</para>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 2.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Łączna wartość przychodów (K_8) w ewidencji przychodów w okresie, którego dotyczy" +
            " JPK_EWP")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("SumaPrzychodow")]
        public decimal SumaPrzychodow { get; set; }
    }
