using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace ProFak.DB
{
	class DaneStartowe
	{
		public static void Zaladuj(Baza baza)
		{
			if (!baza.JednostkiMiar.Any())
			{
				baza.Zapisz(new JednostkaMiary { CzyDomyslna = true, LiczbaMiescPoPrzecinku = 0, Nazwa = "Sztuka", Skrot = "szt" });
				baza.Zapisz(new JednostkaMiary { CzyDomyslna = false, LiczbaMiescPoPrzecinku = 0, Nazwa = "Komplet", Skrot = "kpl" });
				baza.Zapisz(new JednostkaMiary { CzyDomyslna = false, LiczbaMiescPoPrzecinku = 0, Nazwa = "Godzina", Skrot = "h" });
				baza.Zapisz(new JednostkaMiary { CzyDomyslna = false, LiczbaMiescPoPrzecinku = 3, Nazwa = "Kilogram", Skrot = "kg" });
				baza.Zapisz(new JednostkaMiary { CzyDomyslna = false, LiczbaMiescPoPrzecinku = 3, Nazwa = "Litr", Skrot = "l" });
			}

			if (!baza.Numeratory.Any())
			{
				baza.Zapisz(new Numerator { Przeznaczenie = PrzeznaczenieNumeratora.Faktura, Format = "FV/[Numer]/[Rok]" });
				baza.Zapisz(new Numerator { Przeznaczenie = PrzeznaczenieNumeratora.KorektaSprzedaży, Format = "FK/[Numer]/[Rok]" });
				baza.Zapisz(new Numerator { Przeznaczenie = PrzeznaczenieNumeratora.Proforma, Format = "FP/[Numer]/[Rok]" });
				baza.Zapisz(new Numerator { Przeznaczenie = PrzeznaczenieNumeratora.DowódWewnętrzny, Format = "DW/[Numer]/[Rok]" });
				baza.Zapisz(new Numerator { Przeznaczenie = PrzeznaczenieNumeratora.VatMarża, Format = "FM/[Numer]/[Rok]" });
				baza.Zapisz(new Numerator { Przeznaczenie = PrzeznaczenieNumeratora.KorektaVatMarży, Format = "FKM/[Numer]/[Rok]" });
			}

			if (!baza.SposobyPlatnosci.Any())
			{
				baza.Zapisz(new SposobPlatnosci { CzyDomyslny = true, LiczbaDni = 7, Nazwa = "Przelew 7" });
				baza.Zapisz(new SposobPlatnosci { CzyDomyslny = false, LiczbaDni = 14, Nazwa = "Przelew 14" });
				baza.Zapisz(new SposobPlatnosci { CzyDomyslny = false, LiczbaDni = 30, Nazwa = "Przelew 30" });
				baza.Zapisz(new SposobPlatnosci { CzyDomyslny = false, LiczbaDni = 30, Nazwa = "Przelew, mechanizm podzielonej płatności" });
				baza.Zapisz(new SposobPlatnosci { CzyDomyslny = false, LiczbaDni = 0, Nazwa = "Gotówka" });
				baza.Zapisz(new SposobPlatnosci { CzyDomyslny = false, LiczbaDni = 0, Nazwa = "Karta" });
			}

			if (!baza.StawkiVat.Any())
			{
				baza.Zapisz(new StawkaVat { CzyDomyslna = true, Wartosc = 23, Skrot = "23%" });
				baza.Zapisz(new StawkaVat { CzyDomyslna = false, Wartosc = 8, Skrot = "8%" });
				baza.Zapisz(new StawkaVat { CzyDomyslna = false, Wartosc = 5, Skrot = "5%" });
				baza.Zapisz(new StawkaVat { CzyDomyslna = false, Wartosc = 0, Skrot = "0%" });
				baza.Zapisz(new StawkaVat { CzyDomyslna = false, Wartosc = 0, Skrot = "NP" });
				baza.Zapisz(new StawkaVat { CzyDomyslna = false, Wartosc = 0, Skrot = "ZW" });
			}

			if (!baza.Waluty.Any())
			{
				baza.Zapisz(new Waluta { CzyDomyslna = true, Skrot = "PLN", Nazwa = "Polski złoty" });
			}

			if (!baza.UrzedySkarbowe.Any())
			{
				baza.Zapisz(new UrzadSkarbowy { Kod = "0202", Nazwa = "URZĄD SKARBOWY W BOLESŁAWCU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0203", Nazwa = "URZĄD SKARBOWY W BYSTRZYCY KŁODZKIEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0204", Nazwa = "URZĄD SKARBOWY W DZIERŻONIOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0205", Nazwa = "URZĄD SKARBOWY W GŁOGOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0206", Nazwa = "URZĄD SKARBOWY W JAWORZE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0207", Nazwa = "URZĄD SKARBOWY W JELENIEJ GÓRZE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0208", Nazwa = "URZĄD SKARBOWY W KAMIENNEJ GÓRZE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0209", Nazwa = "URZĄD SKARBOWY W KŁODZKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0210", Nazwa = "URZĄD SKARBOWY W LEGNICY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0211", Nazwa = "URZĄD SKARBOWY W LUBANIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0212", Nazwa = "URZĄD SKARBOWY W LUBINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0213", Nazwa = "URZĄD SKARBOWY W LWÓWKU ŚLĄSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0214", Nazwa = "URZĄD SKARBOWY W MILICZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0215", Nazwa = "URZĄD SKARBOWY W NOWEJ RUDZIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0216", Nazwa = "URZĄD SKARBOWY W OLEŚNICY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0217", Nazwa = "URZĄD SKARBOWY W OŁAWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0218", Nazwa = "URZĄD SKARBOWY W STRZELINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0219", Nazwa = "URZĄD SKARBOWY W ŚRODZIE ŚLĄSKIEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0220", Nazwa = "URZĄD SKARBOWY W ŚWIDNICY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0221", Nazwa = "URZĄD SKARBOWY W TRZEBNICY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0222", Nazwa = "URZĄD SKARBOWY W WAŁBRZYCHU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0223", Nazwa = "URZĄD SKARBOWY W WOŁOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0224", Nazwa = "URZĄD SKARBOWY WROCŁAW-FABRYCZNA" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0225", Nazwa = "URZĄD SKARBOWY WROCŁAW-KRZYKI" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0226", Nazwa = "URZĄD SKARBOWY WROCŁAW-PSIE POLE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0227", Nazwa = "URZĄD SKARBOWY WROCŁAW-STARE MIASTO" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0228", Nazwa = "URZĄD SKARBOWY WROCŁAW-ŚRÓDMIEŚCIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0229", Nazwa = "PIERWSZY URZĄD SKARBOWY WE WROCŁAWIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0230", Nazwa = "URZĄD SKARBOWY W ZĄBKOWICACH ŚLĄSKICH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0231", Nazwa = "URZĄD SKARBOWY W ZGORZELCU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0232", Nazwa = "URZĄD SKARBOWY W ZŁOTORYI" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0233", Nazwa = "URZĄD SKARBOWY W GÓRZE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0234", Nazwa = "URZĄD SKARBOWY W POLKOWICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0271", Nazwa = "DOLNOŚLĄSKI URZĄD SKARBOWY WE WROCŁAWIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0402", Nazwa = "URZĄD SKARBOWY W ALEKSANDROWIE KUJAWSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0403", Nazwa = "URZĄD SKARBOWY W BRODNICY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0404", Nazwa = "PIERWSZY URZĄD SKARBOWY W BYDGOSZCZY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0405", Nazwa = "DRUGI URZĄD SKARBOWY W BYDGOSZCZY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0406", Nazwa = "TRZECI URZĄD SKARBOWY W BYDGOSZCZY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0407", Nazwa = "URZĄD SKARBOWY W CHEŁMNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0408", Nazwa = "URZĄD SKARBOWY W GRUDZIĄDZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0409", Nazwa = "URZĄD SKARBOWY W INOWROCŁAWIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0410", Nazwa = "URZĄD SKARBOWY W LIPNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0411", Nazwa = "URZĄD SKARBOWY W MOGILNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0412", Nazwa = "URZĄD SKARBOWY W NAKLE NAD NOTECIĄ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0413", Nazwa = "URZĄD SKARBOWY W RADZIEJOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0414", Nazwa = "URZĄD SKARBOWY W RYPINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0415", Nazwa = "URZĄD SKARBOWY W ŚWIECIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0416", Nazwa = "PIERWSZY URZĄD SKARBOWY W TORUNIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0417", Nazwa = "DRUGI URZĄD SKARBOWY W TORUNIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0418", Nazwa = "URZĄD SKARBOWY W TUCHOLI" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0419", Nazwa = "URZĄD SKARBOWY W WĄBRZEŹNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0420", Nazwa = "URZĄD SKARBOWY WE WŁOCŁAWKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0421", Nazwa = "URZĄD SKARBOWY W ŻNINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0422", Nazwa = "URZĄD SKARBOWY W GOLUBIU-DOBRZYNIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0423", Nazwa = "URZĄD SKARBOWY W SĘPÓLNIE KRAJEŃSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0471", Nazwa = "KUJAWSKO-POMORSKI URZĄD SKARBOWY W BYDGOSZCZY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0602", Nazwa = "URZĄD SKARBOWY W BIAŁEJ PODLASKIEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0603", Nazwa = "URZĄD SKARBOWY W BIŁGORAJU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0604", Nazwa = "URZĄD SKARBOWY W CHEŁMIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0605", Nazwa = "URZĄD SKARBOWY W HRUBIESZOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0606", Nazwa = "URZĄD SKARBOWY W JANOWIE LUBELSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0607", Nazwa = "URZĄD SKARBOWY W KRASNYMSTAWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0608", Nazwa = "URZĄD SKARBOWY W KRAŚNIKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0609", Nazwa = "URZĄD SKARBOWY W LUBARTOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0610", Nazwa = "PIERWSZY URZĄD SKARBOWY W LUBLINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0611", Nazwa = "DRUGI URZĄD SKARBOWY W LUBLINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0612", Nazwa = "TRZECI URZĄD SKARBOWY W LUBLINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0613", Nazwa = "URZĄD SKARBOWY W ŁUKOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0614", Nazwa = "URZĄD SKARBOWY W OPOLU LUBELSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0615", Nazwa = "URZĄD SKARBOWY W PARCZEWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0616", Nazwa = "URZĄD SKARBOWY W PUŁAWACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0617", Nazwa = "URZĄD SKARBOWY W RADZYNIU PODLASKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0618", Nazwa = "URZĄD SKARBOWY W TOMASZOWIE LUBELSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0619", Nazwa = "URZĄD SKARBOWY WE WŁODAWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0620", Nazwa = "URZĄD SKARBOWY W ZAMOŚCIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0621", Nazwa = "URZĄD SKARBOWY W ŁĘCZNEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0622", Nazwa = "URZĄD SKARBOWY W RYKACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0671", Nazwa = "LUBELSKI URZĄD SKARBOWY W LUBLINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0802", Nazwa = "URZĄD SKARBOWY W GORZOWIE WIELKOPOLSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0803", Nazwa = "URZĄD SKARBOWY W KROŚNIE ODRZAŃSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0804", Nazwa = "URZĄD SKARBOWY W MIĘDZYRZECZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0805", Nazwa = "URZĄD SKARBOWY W NOWEJ SOLI" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0806", Nazwa = "URZĄD SKARBOWY W SŁUBICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0807", Nazwa = "URZĄD SKARBOWY W ŚWIEBODZINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0808", Nazwa = "PIERWSZY URZĄD SKARBOWY W ZIELONEJ GÓRZE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0809", Nazwa = "DRUGI URZĄD SKARBOWY W ZIELONEJ GÓRZE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0810", Nazwa = "URZĄD SKARBOWY W ŻAGANIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0811", Nazwa = "URZĄD SKARBOWY W ŻARACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0812", Nazwa = "URZĄD SKARBOWY W DREZDENKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0813", Nazwa = "URZĄD SKARBOWY W SULĘCINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0814", Nazwa = "URZĄD SKARBOWY WE WSCHOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "0871", Nazwa = "LUBUSKI URZĄD SKARBOWY W ZIELONEJ GÓRZE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1002", Nazwa = "URZĄD SKARBOWY W BEŁCHATOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1003", Nazwa = "URZĄD SKARBOWY W BRZEZINACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1004", Nazwa = "URZĄD SKARBOWY W GŁOWNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1005", Nazwa = "URZĄD SKARBOWY W KUTNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1006", Nazwa = "URZĄD SKARBOWY W ŁASKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1007", Nazwa = "URZĄD SKARBOWY W ŁOWICZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1008", Nazwa = "PIERWSZY URZĄD SKARBOWY ŁÓDŹ-BAŁUTY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1009", Nazwa = "DRUGI URZĄD SKARBOWY ŁÓDŹ-BAŁUTY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1010", Nazwa = "PIERWSZY URZĄD SKARBOWY ŁÓDŹ-GÓRNA" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1011", Nazwa = "DRUGI URZĄD SKARBOWY ŁÓDŹ-GÓRNA" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1012", Nazwa = "URZĄD SKARBOWY ŁÓDŹ-POLESIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1013", Nazwa = "URZĄD SKARBOWY ŁÓDŹ-ŚRÓDMIEŚCIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1014", Nazwa = "URZĄD SKARBOWY ŁÓDŹ-WIDZEW" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1015", Nazwa = "URZĄD SKARBOWY W OPOCZNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1016", Nazwa = "URZĄD SKARBOWY W PABIANICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1017", Nazwa = "URZĄD SKARBOWY W PIOTRKOWIE TRYBUNALSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1018", Nazwa = "URZĄD SKARBOWY W PODDĘBICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1019", Nazwa = "URZĄD SKARBOWY W RADOMSKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1020", Nazwa = "URZĄD SKARBOWY W RAWIE MAZOWIECKIEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1021", Nazwa = "URZĄD SKARBOWY W SIERADZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1022", Nazwa = "URZĄD SKARBOWY W SKIERNIEWICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1023", Nazwa = "URZĄD SKARBOWY W TOMASZOWIE MAZOWIECKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1024", Nazwa = "URZĄD SKARBOWY W WIELUNIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1025", Nazwa = "URZĄD SKARBOWY W ZDUŃSKIEJ WOLI" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1026", Nazwa = "URZĄD SKARBOWY W ZGIERZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1027", Nazwa = "URZĄD SKARBOWY W WIERUSZOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1028", Nazwa = "URZĄD SKARBOWY W ŁĘCZYCY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1029", Nazwa = "URZĄD SKARBOWY W PAJĘCZNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1071", Nazwa = "ŁÓDZKI URZĄD SKARBOWY W ŁODZI" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1202", Nazwa = "URZĄD SKARBOWY W BOCHNI" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1203", Nazwa = "URZĄD SKARBOWY W BRZESKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1204", Nazwa = "URZĄD SKARBOWY W CHRZANOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1205", Nazwa = "URZĄD SKARBOWY W DĄBROWIE TARNOWSKIEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1206", Nazwa = "URZĄD SKARBOWY W GORLICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1207", Nazwa = "PIERWSZY URZĄD SKARBOWY KRAKÓW" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1208", Nazwa = "URZĄD SKARBOWY KRAKÓW-KROWODRZA" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1209", Nazwa = "URZĄD SKARBOWY KRAKÓW-NOWA HUTA" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1210", Nazwa = "URZĄD SKARBOWY KRAKÓW-PODGÓRZE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1211", Nazwa = "URZĄD SKARBOWY KRAKÓW-PRĄDNIK" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1212", Nazwa = "URZĄD SKARBOWY KRAKÓW-STARE MIASTO" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1213", Nazwa = "URZĄD SKARBOWY KRAKÓW-ŚRÓDMIEŚCIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1214", Nazwa = "URZĄD SKARBOWY W LIMANOWEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1215", Nazwa = "URZĄD SKARBOWY W MIECHOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1216", Nazwa = "URZĄD SKARBOWY W MYŚLENICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1217", Nazwa = "URZĄD SKARBOWY W NOWYM SĄCZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1218", Nazwa = "URZĄD SKARBOWY W NOWYM TARGU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1219", Nazwa = "URZĄD SKARBOWY W OLKUSZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1220", Nazwa = "URZĄD SKARBOWY W OŚWIĘCIMIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1221", Nazwa = "URZĄD SKARBOWY W PROSZOWICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1222", Nazwa = "URZĄD SKARBOWY W SUCHEJ BESKIDZKIEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1223", Nazwa = "PIERWSZY URZĄD SKARBOWY W TARNOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1224", Nazwa = "DRUGI URZĄD SKARBOWY W TARNOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1225", Nazwa = "URZĄD SKARBOWY W WADOWICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1226", Nazwa = "URZĄD SKARBOWY W WIELICZCE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1227", Nazwa = "URZĄD SKARBOWY W ZAKOPANEM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1228", Nazwa = "DRUGI URZĄD SKARBOWY KRAKÓW" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1271", Nazwa = "MAŁOPOLSKI URZĄD SKARBOWY W KRAKOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1402", Nazwa = "URZĄD SKARBOWY W BIAŁOBRZEGACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1403", Nazwa = "URZĄD SKARBOWY W CIECHANOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1404", Nazwa = "URZĄD SKARBOWY W GARWOLINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1405", Nazwa = "URZĄD SKARBOWY W GOSTYNINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1406", Nazwa = "URZĄD SKARBOWY W GRODZISKU MAZOWIECKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1407", Nazwa = "URZĄD SKARBOWY W GRÓJCU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1408", Nazwa = "URZĄD SKARBOWY W KOZIENICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1409", Nazwa = "URZĄD SKARBOWY W LEGIONOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1410", Nazwa = "URZĄD SKARBOWY W ŁOSICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1411", Nazwa = "URZĄD SKARBOWY W MAKOWIE MAZOWIECKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1412", Nazwa = "URZĄD SKARBOWY W MIŃSKU MAZOWIECKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1413", Nazwa = "URZĄD SKARBOWY W MŁAWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1414", Nazwa = "URZĄD SKARBOWY W NOWYM DWORZE MAZOWIECKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1415", Nazwa = "URZĄD SKARBOWY W OSTROŁĘCE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1416", Nazwa = "URZĄD SKARBOWY W OSTROWI MAZOWIECKIEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1417", Nazwa = "URZĄD SKARBOWY W OTWOCKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1418", Nazwa = "URZĄD SKARBOWY W PIASECZNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1419", Nazwa = "URZĄD SKARBOWY W PŁOCKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1420", Nazwa = "URZĄD SKARBOWY W PŁOŃSKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1421", Nazwa = "URZĄD SKARBOWY W PRUSZKOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1422", Nazwa = "URZĄD SKARBOWY W PRZASNYSZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1423", Nazwa = "URZĄD SKARBOWY W PUŁTUSKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1424", Nazwa = "PIERWSZY URZĄD SKARBOWY W RADOMIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1425", Nazwa = "DRUGI URZĄD SKARBOWY W RADOMIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1426", Nazwa = "URZĄD SKARBOWY W SIEDLCACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1427", Nazwa = "URZĄD SKARBOWY W SIERPCU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1428", Nazwa = "URZĄD SKARBOWY W SOCHACZEWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1429", Nazwa = "URZĄD SKARBOWY W SOKOŁOWIE PODLASKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1430", Nazwa = "URZĄD SKARBOWY W SZYDŁOWCU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1431", Nazwa = "URZĄD SKARBOWY WARSZAWA-BEMOWO" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1432", Nazwa = "URZĄD SKARBOWY WARSZAWA-BIELANY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1433", Nazwa = "URZĄD SKARBOWY WARSZAWA-MOKOTÓW" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1434", Nazwa = "URZĄD SKARBOWY WARSZAWA-PRAGA" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1435", Nazwa = "PIERWSZY URZĄD SKARBOWY WARSZAWA-ŚRÓDMIEŚCIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1436", Nazwa = "DRUGI URZĄD SKARBOWY WARSZAWA-ŚRÓDMIEŚCIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1437", Nazwa = "URZĄD SKARBOWY WARSZAWA-TARGÓWEK" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1438", Nazwa = "URZĄD SKARBOWY WARSZAWA-URSYNÓW" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1439", Nazwa = "URZĄD SKARBOWY WARSZAWA-WAWER" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1440", Nazwa = "URZĄD SKARBOWY WARSZAWA-WOLA" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1441", Nazwa = "URZĄD SKARBOWY W WĘGROWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1442", Nazwa = "URZĄD SKARBOWY W WOŁOMINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1443", Nazwa = "URZĄD SKARBOWY W WYSZKOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1444", Nazwa = "URZĄD SKARBOWY W ZWOLENIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1445", Nazwa = "URZĄD SKARBOWY W ŻUROMINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1446", Nazwa = "URZĄD SKARBOWY W ŻYRARDOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1447", Nazwa = "URZĄD SKARBOWY W LIPSKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1448", Nazwa = "URZĄD SKARBOWY W PRZYSUSZE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1449", Nazwa = "TRZECI URZĄD SKARBOWY WARSZAWA-ŚRÓDMIEŚCIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1471", Nazwa = "PIERWSZY MAZOWIECKI URZĄD SKARBOWY W WARSZAWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1472", Nazwa = "DRUGI MAZOWIECKI URZĄD SKARBOWY W WARSZAWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1473", Nazwa = "TRZECI MAZOWIECKI URZĄD SKARBOWY W RADOMIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1602", Nazwa = "URZĄD SKARBOWY W BRZEGU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1603", Nazwa = "URZĄD SKARBOWY W GŁUBCZYCACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1604", Nazwa = "URZĄD SKARBOWY W KĘDZIERZYNIE-KOŹLU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1605", Nazwa = "URZĄD SKARBOWY W KLUCZBORKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1606", Nazwa = "URZĄD SKARBOWY W NAMYSŁOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1607", Nazwa = "URZĄD SKARBOWY W NYSIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1608", Nazwa = "URZĄD SKARBOWY W OLEŚNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1609", Nazwa = "PIERWSZY URZĄD SKARBOWY W OPOLU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1610", Nazwa = "DRUGI URZĄD SKARBOWY W OPOLU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1611", Nazwa = "URZĄD SKARBOWY W PRUDNIKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1612", Nazwa = "URZĄD SKARBOWY W STRZELCACH OPOLSKICH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1613", Nazwa = "URZĄD SKARBOWY W KRAPKOWICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1671", Nazwa = "OPOLSKI URZĄD SKARBOWY W OPOLU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1802", Nazwa = "URZĄD SKARBOWY W BRZOZOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1803", Nazwa = "URZĄD SKARBOWY W DĘBICY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1804", Nazwa = "URZĄD SKARBOWY W JAROSŁAWIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1805", Nazwa = "URZĄD SKARBOWY W JAŚLE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1806", Nazwa = "URZĄD SKARBOWY W KOLBUSZOWEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1807", Nazwa = "URZĄD SKARBOWY W KROŚNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1808", Nazwa = "URZĄD SKARBOWY W LESKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1809", Nazwa = "URZĄD SKARBOWY W LEŻAJSKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1810", Nazwa = "URZĄD SKARBOWY W LUBACZOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1811", Nazwa = "URZĄD SKARBOWY W ŁAŃCUCIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1812", Nazwa = "URZĄD SKARBOWY W MIELCU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1813", Nazwa = "URZĄD SKARBOWY W PRZEMYŚLU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1814", Nazwa = "URZĄD SKARBOWY W PRZEWORSKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1815", Nazwa = "URZĄD SKARBOWY W ROPCZYCACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1816", Nazwa = "PIERWSZY URZĄD SKARBOWY W RZESZOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1817", Nazwa = "URZĄD SKARBOWY W SANOKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1818", Nazwa = "URZĄD SKARBOWY W STALOWEJ WOLI" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1819", Nazwa = "URZĄD SKARBOWY W STRZYŻOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1820", Nazwa = "URZĄD SKARBOWY W TARNOBRZEGU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1821", Nazwa = "URZĄD SKARBOWY W USTRZYKACH DOLNYCH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1822", Nazwa = "DRUGI URZĄD SKARBOWY W RZESZOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1823", Nazwa = "URZĄD SKARBOWY W NISKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "1871", Nazwa = "PODKARPACKI URZĄD SKARBOWY W RZESZOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2002", Nazwa = "URZĄD SKARBOWY W AUGUSTOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2003", Nazwa = "PIERWSZY URZĄD SKARBOWY W BIAŁYMSTOKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2004", Nazwa = "DRUGI URZĄD SKARBOWY W BIAŁYMSTOKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2005", Nazwa = "URZĄD SKARBOWY W BIELSKU PODLASKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2006", Nazwa = "URZĄD SKARBOWY W GRAJEWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2007", Nazwa = "URZĄD SKARBOWY W KOLNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2008", Nazwa = "URZĄD SKARBOWY W ŁOMŻY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2009", Nazwa = "URZĄD SKARBOWY W MOŃKACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2010", Nazwa = "URZĄD SKARBOWY W SIEMIATYCZACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2011", Nazwa = "URZĄD SKARBOWY W SOKÓŁCE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2012", Nazwa = "URZĄD SKARBOWY W SUWAŁKACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2013", Nazwa = "URZĄD SKARBOWY W WYSOKIEM MAZOWIECKIEM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2014", Nazwa = "URZĄD SKARBOWY W ZAMBROWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2015", Nazwa = "URZĄD SKARBOWY W HAJNÓWCE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2071", Nazwa = "PODLASKI URZĄD SKARBOWY W BIAŁYMSTOKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2202", Nazwa = "URZĄD SKARBOWY W BYTOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2203", Nazwa = "URZĄD SKARBOWY W CHOJNICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2204", Nazwa = "URZĄD SKARBOWY W CZŁUCHOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2205", Nazwa = "PIERWSZY URZĄD SKARBOWY W GDAŃSKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2206", Nazwa = "DRUGI URZĄD SKARBOWY W GDAŃSKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2207", Nazwa = "TRZECI URZĄD SKARBOWY W GDAŃSKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2208", Nazwa = "PIERWSZY URZĄD SKARBOWY W GDYNI" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2209", Nazwa = "DRUGI URZĄD SKARBOWY W GDYNI" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2210", Nazwa = "URZĄD SKARBOWY W KARTUZACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2211", Nazwa = "URZĄD SKARBOWY W KOŚCIERZYNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2212", Nazwa = "URZĄD SKARBOWY W KWIDZYNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2213", Nazwa = "URZĄD SKARBOWY W LĘBORKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2214", Nazwa = "URZĄD SKARBOWY W MALBORKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2215", Nazwa = "URZĄD SKARBOWY W PUCKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2216", Nazwa = "URZĄD SKARBOWY W SŁUPSKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2217", Nazwa = "URZĄD SKARBOWY W SOPOCIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2218", Nazwa = "URZĄD SKARBOWY W STAROGARDZIE GDAŃSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2219", Nazwa = "URZĄD SKARBOWY W TCZEWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2220", Nazwa = "URZĄD SKARBOWY W WEJHEROWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2221", Nazwa = "URZĄD SKARBOWY W PRUSZCZU GDAŃSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2271", Nazwa = "POMORSKI URZĄD SKARBOWY W GDAŃSKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2402", Nazwa = "URZĄD SKARBOWY W BĘDZINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2403", Nazwa = "PIERWSZY URZĄD SKARBOWY W BIELSKU-BIAŁEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2404", Nazwa = "DRUGI URZĄD SKARBOWY W BIELSKU-BIAŁEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2405", Nazwa = "URZĄD SKARBOWY W BYTOMIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2406", Nazwa = "URZĄD SKARBOWY W CHORZOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2407", Nazwa = "URZĄD SKARBOWY W CIESZYNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2408", Nazwa = "URZĄD SKARBOWY W CZECHOWICACH-DZIEDZICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2409", Nazwa = "PIERWSZY URZĄD SKARBOWY W CZĘSTOCHOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2410", Nazwa = "DRUGI URZĄD SKARBOWY W CZĘSTOCHOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2411", Nazwa = "URZĄD SKARBOWY W DĄBROWIE GÓRNICZEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2412", Nazwa = "PIERWSZY URZĄD SKARBOWY W GLIWICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2413", Nazwa = "DRUGI URZĄD SKARBOWY W GLIWICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2414", Nazwa = "URZĄD SKARBOWY W JASTRZĘBIU-ZDROJU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2415", Nazwa = "URZĄD SKARBOWY W JAWORZNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2416", Nazwa = "PIERWSZY URZĄD SKARBOWY W KATOWICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2417", Nazwa = "DRUGI URZĄD SKARBOWY W KATOWICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2418", Nazwa = "URZĄD SKARBOWY W KŁOBUCKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2419", Nazwa = "URZĄD SKARBOWY W LUBLIŃCU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2420", Nazwa = "URZĄD SKARBOWY W MIKOŁOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2421", Nazwa = "URZĄD SKARBOWY W MYSŁOWICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2422", Nazwa = "URZĄD SKARBOWY W MYSZKOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2423", Nazwa = "URZĄD SKARBOWY W PIEKARACH ŚLĄSKICH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2424", Nazwa = "URZĄD SKARBOWY W PSZCZYNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2425", Nazwa = "URZĄD SKARBOWY W RACIBORZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2426", Nazwa = "URZĄD SKARBOWY W RUDZIE ŚLĄSKIEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2427", Nazwa = "URZĄD SKARBOWY W RYBNIKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2428", Nazwa = "URZĄD SKARBOWY W SIEMIANOWICACH ŚLĄSKICH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2429", Nazwa = "URZĄD SKARBOWY W SOSNOWCU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2430", Nazwa = "URZĄD SKARBOWY W TARNOWSKICH GÓRACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2431", Nazwa = "URZĄD SKARBOWY W TYCHACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2432", Nazwa = "URZĄD SKARBOWY W WODZISŁAWIU ŚLĄSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2433", Nazwa = "URZĄD SKARBOWY W ZABRZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2434", Nazwa = "URZĄD SKARBOWY W ZAWIERCIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2435", Nazwa = "URZĄD SKARBOWY W ŻORACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2436", Nazwa = "URZĄD SKARBOWY W ŻYWCU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2471", Nazwa = "PIERWSZY ŚLĄSKI URZĄD SKARBOWY W SOSNOWCU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2472", Nazwa = "DRUGI ŚLĄSKI URZĄD SKARBOWY W BIELSKU-BIAŁEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2602", Nazwa = "URZĄD SKARBOWY W BUSKU-ZDROJU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2603", Nazwa = "URZĄD SKARBOWY W JĘDRZEJOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2604", Nazwa = "PIERWSZY URZĄD SKARBOWY W KIELCACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2605", Nazwa = "DRUGI URZĄD SKARBOWY W KIELCACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2606", Nazwa = "URZĄD SKARBOWY W KOŃSKICH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2607", Nazwa = "URZĄD SKARBOWY W OPATOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2608", Nazwa = "URZĄD SKARBOWY W OSTROWCU ŚWIĘTOKRZYSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2609", Nazwa = "URZĄD SKARBOWY W PIŃCZOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2610", Nazwa = "URZĄD SKARBOWY W SANDOMIERZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2611", Nazwa = "URZĄD SKARBOWY W SKARŻYSKU-KAMIENNEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2612", Nazwa = "URZĄD SKARBOWY W STARACHOWICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2613", Nazwa = "URZĄD SKARBOWY W STASZOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2614", Nazwa = "URZĄD SKARBOWY W KAZIMIERZY WIELKIEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2615", Nazwa = "URZĄD SKARBOWY WE WŁOSZCZOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2671", Nazwa = "ŚWIĘTOKRZYSKI URZĄD SKARBOWY W KIELCACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2802", Nazwa = "URZĄD SKARBOWY W BARTOSZYCACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2803", Nazwa = "URZĄD SKARBOWY W BRANIEWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2804", Nazwa = "URZĄD SKARBOWY W DZIAŁDOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2805", Nazwa = "URZĄD SKARBOWY W ELBLĄGU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2806", Nazwa = "URZĄD SKARBOWY W EŁKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2807", Nazwa = "URZĄD SKARBOWY W GIŻYCKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2808", Nazwa = "URZĄD SKARBOWY W IŁAWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2809", Nazwa = "URZĄD SKARBOWY W KĘTRZYNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2810", Nazwa = "URZĄD SKARBOWY W NIDZICY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2811", Nazwa = "URZĄD SKARBOWY W NOWYM MIEŚCIE LUBAWSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2812", Nazwa = "URZĄD SKARBOWY W OLECKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2813", Nazwa = "URZĄD SKARBOWY W OLSZTYNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2814", Nazwa = "URZĄD SKARBOWY W OSTRÓDZIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2815", Nazwa = "URZĄD SKARBOWY W PISZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2816", Nazwa = "URZĄD SKARBOWY W SZCZYTNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "2871", Nazwa = "WARMIŃSKO-MAZURSKI URZĄD SKARBOWY W OLSZTYNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3002", Nazwa = "URZĄD SKARBOWY W CZARNKOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3003", Nazwa = "URZĄD SKARBOWY W GNIEŹNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3004", Nazwa = "URZĄD SKARBOWY W GOSTYNIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3005", Nazwa = "URZĄD SKARBOWY W GRODZISKU WIELKOPOLSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3006", Nazwa = "URZĄD SKARBOWY W JAROCINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3007", Nazwa = "PIERWSZY URZĄD SKARBOWY W KALISZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3008", Nazwa = "DRUGI URZĄD SKARBOWY W KALISZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3009", Nazwa = "URZĄD SKARBOWY W KĘPNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3010", Nazwa = "URZĄD SKARBOWY W KOLE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3011", Nazwa = "URZĄD SKARBOWY W KONINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3012", Nazwa = "URZĄD SKARBOWY W KOŚCIANIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3013", Nazwa = "URZĄD SKARBOWY W KROTOSZYNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3014", Nazwa = "URZĄD SKARBOWY W LESZNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3015", Nazwa = "URZĄD SKARBOWY W MIĘDZYCHODZIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3016", Nazwa = "URZĄD SKARBOWY W NOWYM TOMYŚLU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3017", Nazwa = "URZĄD SKARBOWY W OSTROWIE WIELKOPOLSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3018", Nazwa = "URZĄD SKARBOWY W OSTRZESZOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3019", Nazwa = "URZĄD SKARBOWY W PILE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3020", Nazwa = "URZĄD SKARBOWY POZNAŃ-GRUNWALD" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3021", Nazwa = "URZĄD SKARBOWY POZNAŃ-JEŻYCE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3022", Nazwa = "URZĄD SKARBOWY POZNAŃ-NOWE MIASTO" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3023", Nazwa = "PIERWSZY URZĄD SKARBOWY W POZNANIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3025", Nazwa = "URZĄD SKARBOWY POZNAŃ-WINOGRADY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3026", Nazwa = "URZĄD SKARBOWY POZNAŃ-WILDA" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3027", Nazwa = "URZĄD SKARBOWY W RAWICZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3028", Nazwa = "URZĄD SKARBOWY W SŁUPCY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3029", Nazwa = "URZĄD SKARBOWY W SZAMOTUŁACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3030", Nazwa = "URZĄD SKARBOWY W ŚREMIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3031", Nazwa = "URZĄD SKARBOWY W ŚRODZIE WIELKOPOLSKIEJ" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3032", Nazwa = "URZĄD SKARBOWY W TURKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3033", Nazwa = "URZĄD SKARBOWY W WĄGROWCU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3034", Nazwa = "URZĄD SKARBOWY W WOLSZTYNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3035", Nazwa = "URZĄD SKARBOWY WE WRZEŚNI" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3036", Nazwa = "URZĄD SKARBOWY W ZŁOTOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3037", Nazwa = "URZĄD SKARBOWY W CHODZIEŻY" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3038", Nazwa = "URZĄD SKARBOWY W OBORNIKACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3039", Nazwa = "URZĄD SKARBOWY W PLESZEWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3071", Nazwa = "PIERWSZY WIELKOPOLSKI URZĄD SKARBOWY W POZNANIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3072", Nazwa = "DRUGI WIELKOPOLSKI URZĄD SKARBOWY W KALISZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3202", Nazwa = "URZĄD SKARBOWY W BIAŁOGARDZIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3203", Nazwa = "URZĄD SKARBOWY W CHOSZCZNIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3204", Nazwa = "URZĄD SKARBOWY W DRAWSKU POMORSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3205", Nazwa = "URZĄD SKARBOWY W GOLENIOWIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3206", Nazwa = "URZĄD SKARBOWY W GRYFICACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3207", Nazwa = "URZĄD SKARBOWY W GRYFINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3208", Nazwa = "URZĄD SKARBOWY W KAMIENIU POMORSKIM" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3209", Nazwa = "URZĄD SKARBOWY W KOŁOBRZEGU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3210", Nazwa = "PIERWSZY URZĄD SKARBOWY W KOSZALINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3211", Nazwa = "DRUGI URZĄD SKARBOWY W KOSZALINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3212", Nazwa = "URZĄD SKARBOWY W MYŚLIBORZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3213", Nazwa = "URZĄD SKARBOWY W PYRZYCACH" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3214", Nazwa = "URZĄD SKARBOWY W STARGARDZIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3215", Nazwa = "PIERWSZY URZĄD SKARBOWY W SZCZECINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3216", Nazwa = "DRUGI URZĄD SKARBOWY W SZCZECINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3217", Nazwa = "TRZECI URZĄD SKARBOWY W SZCZECINIE" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3218", Nazwa = "URZĄD SKARBOWY W SZCZECINKU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3219", Nazwa = "URZĄD SKARBOWY W ŚWINOUJŚCIU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3220", Nazwa = "URZĄD SKARBOWY W WAŁCZU" });
				baza.Zapisz(new UrzadSkarbowy { Kod = "3271", Nazwa = "ZACHODNIOPOMORSKI URZĄD SKARBOWY W SZCZECINIE" });
			}
		}
	}
}
