// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProFak.DB;

#nullable disable

namespace ProFak.DB.MigrationsSqlServer
{
    [DbContext(typeof(BazaSqlServer))]
    partial class BazaSqlServerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProFak.DB.DeklaracjaVat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Miesiac")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Nalezny23")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Nalezny5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Nalezny8")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NaleznyWNT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NaliczonyPozostale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NaliczonyPrzeniesiony")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NaliczonySrodkiTrwale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Netto0")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Netto23")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Netto5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Netto8")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NettoPozostale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NettoSrodkiTrwale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NettoWDT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NettoWNT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NettoZW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("DeklaracjaVat", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.DodatkowyPodmiot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int>("FakturaId")
                        .HasColumnType("int");

                    b.Property<string>("IDwew")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("NIP")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int>("Rodzaj")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<decimal?>("Udzial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VatUE")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("FakturaId");

                    b.ToTable("DodatkowyPodmiot", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.Faktura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyTP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CzyWDT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CzyWNT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CzyWartosciReczne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CzyZakupSrodkowTrwalych")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DaneNabywcy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("DaneSprzedawcy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("DataKSeF")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSprzedazy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUsuniecia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWprowadzenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataWyslania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWystawienia")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeklaracjaVatId")
                        .HasColumnType("int");

                    b.Property<int?>("FakturaKorygowanaId")
                        .HasColumnType("int");

                    b.Property<int?>("FakturaKorygujacaId")
                        .HasColumnType("int");

                    b.Property<int?>("FakturaPierwotnaId")
                        .HasColumnType("int");

                    b.Property<decimal>("KursWaluty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(1m);

                    b.Property<string>("NIPNabywcy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("NIPSprzedawcy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int?>("NabywcaId")
                        .HasColumnType("int");

                    b.Property<string>("NazwaBanku")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("NazwaNabywcy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("NazwaSprzedawcy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Numer")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("NumerKSeF")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("OpisSposobuPlatnosci")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("OpisZdarzenia")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int>("ProceduraMarzy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("ProcentKosztow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(100m);

                    b.Property<decimal>("ProcentVatNaliczonego")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(100m);

                    b.Property<string>("RachunekBankowy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<decimal>("RazemBrutto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("RazemNetto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("RazemVat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("Rodzaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("SposobPlatnosciId")
                        .HasColumnType("int");

                    b.Property<int?>("SprzedawcaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TerminPlatnosci")
                        .HasColumnType("datetime2");

                    b.Property<string>("URLKSeF")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("UwagiPubliczne")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("UwagiWewnetrzne")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int?>("WalutaId")
                        .HasColumnType("int");

                    b.Property<string>("XMLKSeF")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int?>("ZaliczkaPitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeklaracjaVatId");

                    b.HasIndex("FakturaKorygowanaId");

                    b.HasIndex("FakturaKorygujacaId");

                    b.HasIndex("FakturaPierwotnaId");

                    b.HasIndex("NabywcaId");

                    b.HasIndex("SposobPlatnosciId");

                    b.HasIndex("SprzedawcaId");

                    b.HasIndex("WalutaId");

                    b.HasIndex("ZaliczkaPitId");

                    b.ToTable("Faktura", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.JednostkaMiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyDomyslna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LiczbaMiescPoPrzecinku")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Skrot")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.ToTable("JednostkaMiary", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.KolumnaSpisu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kolejnosc")
                        .HasColumnType("int");

                    b.Property<string>("Kolumna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PoziomSortowania")
                        .HasColumnType("int");

                    b.Property<string>("Spis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Szerokosc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KolumnaSpisu", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.Konfiguracja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EMailNadawca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMailTemat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMailTresc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SMTPHaslo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SMTPLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SMTPPort")
                        .HasColumnType("int");

                    b.Property<string>("SMTPSerwer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Konfiguracja", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EMailNadawca = "[SPRZEDAWCA-NAZWA] <[SPRZEDAWCA-EMAIL]>",
                            EMailTemat = "Faktura - [NUMER]",
                            EMailTresc = "Dzień dobry,\r\n\r\nw załączniku znajduje się faktura numer [NUMER] z dnia [DATA-SPRZEDAZY] na kwotę [KWOTA-BRUTTO] [WALUTA].\r\n\r\nWiadomość wygenerowana automatycznie.\r\n\r\n-- \r\n[SPRZEDAWCA-NAZWA]\r\n[SPRZEDAWCA-ADRES]",
                            SMTPHaslo = "tajnehaslo",
                            SMTPLogin = "biuro",
                            SMTPPort = 465,
                            SMTPSerwer = "smtp.example.com"
                        });
                });

            modelBuilder.Entity("ProFak.DB.Kontrahent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresKorespondencyjny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("AdresRejestrowy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<bool>("CzyArchiwalny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CzyPodmiot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CzyTP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("EMail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int?>("FormaOpodatkowania")
                        .HasColumnType("int");

                    b.Property<string>("KodUrzedu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("NIP")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("NazwaBanku")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("OsobaFizycznaDataUrodzenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("OsobaFizycznaImie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("OsobaFizycznaNazwisko")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("PelnaNazwa")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("RachunekBankowy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int?>("SposobPlatnosciId")
                        .HasColumnType("int");

                    b.Property<int>("SrodowiskoKSeF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Telefon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("TokenKSeF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("UwagiPubliczne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("UwagiWewnetrzne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("SposobPlatnosciId");

                    b.ToTable("Kontrahent", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.Numerator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Format")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int>("Przeznaczenie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Numerator", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.Plik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FakturaId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int>("Rozmiar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ZawartoscId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FakturaId");

                    b.ToTable("Plik", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.PozycjaFaktury", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaBrutto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CenaNetto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CenaVat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CenaZakupuDlaMarzy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("CzyPrzedKorekta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CzyWartosciReczne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CzyWedlugCenBrutto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("FakturaId")
                        .HasColumnType("int");

                    b.Property<int>("GTU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Ilosc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("JednostkaMiaryId")
                        .HasColumnType("int");

                    b.Property<int>("LP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Opis")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<decimal>("RabatCena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("RabatProcent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("RabatWartosc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("StawkaRyczaltu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StawkaVatId")
                        .HasColumnType("int");

                    b.Property<int?>("TowarId")
                        .HasColumnType("int");

                    b.Property<decimal>("WartoscBrutto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("WartoscNetto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("WartoscVat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("FakturaId");

                    b.HasIndex("JednostkaMiaryId");

                    b.HasIndex("StawkaVatId");

                    b.HasIndex("TowarId");

                    b.ToTable("PozycjaFaktury", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.SkladkaZus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Miesiac")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OdliczenieOdDochodu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PodstawaSpoleczne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PodstawaZdrowotne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("RozliczenieRoczneSkladkiZdrowotnej")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("SkladkaEmerytalna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("SkladkaFunduszPracy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("SkladkaRentowa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("SkladkaSpoleczna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("SkladkaWypadkowa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("SkladkaZdrowotna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("SumaSkladek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("SkladkaZus", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.SposobPlatnosci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyDomyslny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LiczbaDni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.ToTable("SposobPlatnosci", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.StanMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyAktywna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CzyUkryta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CzyZwinieta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Pozycja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StanMenu", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.StanNumeratora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumeratorId")
                        .HasColumnType("int");

                    b.Property<int>("OstatniaWartosc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Parametry")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("NumeratorId");

                    b.ToTable("StanNumeratora", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.StawkaVat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyDomyslna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Skrot")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<decimal>("Wartosc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("StawkaVat", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.Towar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaBrutto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CenaNetto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("CzyArchiwalny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CzyWedlugCenBrutto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("GTU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("JednostkaMiaryId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int>("Rodzaj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("StawkaRyczaltu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StawkaVatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JednostkaMiaryId");

                    b.HasIndex("StawkaVatId");

                    b.ToTable("Towar", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.UrzadSkarbowy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UrzadSkarbowy", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.Waluta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyDomyslna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Skrot")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.ToTable("Waluta", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.Wplata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("FakturaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Kwota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Uwagi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("FakturaId");

                    b.ToTable("Wplata", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.ZaliczkaPit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DoPrzeniesienia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("DoWplaty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Koszty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("Miesiac")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Podatek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Przeniesiony")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Przychody")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("SkladkiZus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("ZaliczkaPit", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.Zawartosc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Dane")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("PlikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlikId")
                        .IsUnique()
                        .HasFilter("[PlikId] IS NOT NULL");

                    b.ToTable("Zawartosc", (string)null);
                });

            modelBuilder.Entity("ProFak.DB.DodatkowyPodmiot", b =>
                {
                    b.HasOne("ProFak.DB.Faktura", "Faktura")
                        .WithMany("DodatkowePodmioty")
                        .HasForeignKey("FakturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faktura");
                });

            modelBuilder.Entity("ProFak.DB.Faktura", b =>
                {
                    b.HasOne("ProFak.DB.DeklaracjaVat", "DeklaracjaVat")
                        .WithMany("Faktury")
                        .HasForeignKey("DeklaracjaVatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProFak.DB.Faktura", "FakturaKorygowana")
                        .WithMany()
                        .HasForeignKey("FakturaKorygowanaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProFak.DB.Faktura", "FakturaKorygujaca")
                        .WithMany()
                        .HasForeignKey("FakturaKorygujacaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProFak.DB.Faktura", "FakturaPierwotna")
                        .WithMany()
                        .HasForeignKey("FakturaPierwotnaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProFak.DB.Kontrahent", "Nabywca")
                        .WithMany()
                        .HasForeignKey("NabywcaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProFak.DB.SposobPlatnosci", "SposobPlatnosci")
                        .WithMany()
                        .HasForeignKey("SposobPlatnosciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProFak.DB.Kontrahent", "Sprzedawca")
                        .WithMany()
                        .HasForeignKey("SprzedawcaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProFak.DB.Waluta", "Waluta")
                        .WithMany()
                        .HasForeignKey("WalutaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProFak.DB.ZaliczkaPit", "ZaliczkaPit")
                        .WithMany("Faktury")
                        .HasForeignKey("ZaliczkaPitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DeklaracjaVat");

                    b.Navigation("FakturaKorygowana");

                    b.Navigation("FakturaKorygujaca");

                    b.Navigation("FakturaPierwotna");

                    b.Navigation("Nabywca");

                    b.Navigation("SposobPlatnosci");

                    b.Navigation("Sprzedawca");

                    b.Navigation("Waluta");

                    b.Navigation("ZaliczkaPit");
                });

            modelBuilder.Entity("ProFak.DB.Kontrahent", b =>
                {
                    b.HasOne("ProFak.DB.SposobPlatnosci", "SposobPlatnosci")
                        .WithMany()
                        .HasForeignKey("SposobPlatnosciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SposobPlatnosci");
                });

            modelBuilder.Entity("ProFak.DB.Plik", b =>
                {
                    b.HasOne("ProFak.DB.Faktura", "Faktura")
                        .WithMany("Pliki")
                        .HasForeignKey("FakturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faktura");
                });

            modelBuilder.Entity("ProFak.DB.PozycjaFaktury", b =>
                {
                    b.HasOne("ProFak.DB.Faktura", "Faktura")
                        .WithMany("Pozycje")
                        .HasForeignKey("FakturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProFak.DB.JednostkaMiary", "JednostkaMiary")
                        .WithMany()
                        .HasForeignKey("JednostkaMiaryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProFak.DB.StawkaVat", "StawkaVat")
                        .WithMany()
                        .HasForeignKey("StawkaVatId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProFak.DB.Towar", "Towar")
                        .WithMany()
                        .HasForeignKey("TowarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Faktura");

                    b.Navigation("JednostkaMiary");

                    b.Navigation("StawkaVat");

                    b.Navigation("Towar");
                });

            modelBuilder.Entity("ProFak.DB.StanNumeratora", b =>
                {
                    b.HasOne("ProFak.DB.Numerator", "Numerator")
                        .WithMany("Stany")
                        .HasForeignKey("NumeratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Numerator");
                });

            modelBuilder.Entity("ProFak.DB.Towar", b =>
                {
                    b.HasOne("ProFak.DB.JednostkaMiary", "JednostkaMiary")
                        .WithMany()
                        .HasForeignKey("JednostkaMiaryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProFak.DB.StawkaVat", "StawkaVat")
                        .WithMany()
                        .HasForeignKey("StawkaVatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("JednostkaMiary");

                    b.Navigation("StawkaVat");
                });

            modelBuilder.Entity("ProFak.DB.Wplata", b =>
                {
                    b.HasOne("ProFak.DB.Faktura", "Faktura")
                        .WithMany("Wplaty")
                        .HasForeignKey("FakturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faktura");
                });

            modelBuilder.Entity("ProFak.DB.Zawartosc", b =>
                {
                    b.HasOne("ProFak.DB.Plik", "Plik")
                        .WithOne("Zawartosc")
                        .HasForeignKey("ProFak.DB.Zawartosc", "PlikId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Plik");
                });

            modelBuilder.Entity("ProFak.DB.DeklaracjaVat", b =>
                {
                    b.Navigation("Faktury");
                });

            modelBuilder.Entity("ProFak.DB.Faktura", b =>
                {
                    b.Navigation("DodatkowePodmioty");

                    b.Navigation("Pliki");

                    b.Navigation("Pozycje");

                    b.Navigation("Wplaty");
                });

            modelBuilder.Entity("ProFak.DB.Numerator", b =>
                {
                    b.Navigation("Stany");
                });

            modelBuilder.Entity("ProFak.DB.Plik", b =>
                {
                    b.Navigation("Zawartosc");
                });

            modelBuilder.Entity("ProFak.DB.ZaliczkaPit", b =>
                {
                    b.Navigation("Faktury");
                });
#pragma warning restore 612, 618
        }
    }
}
